// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ApiKeyHasPermissionProcedure from "../api_key_has_permission_procedure";
import * as CreateApiKeyProcedure from "../create_api_key_procedure";
import * as GetFileProcedure from "../get_file_procedure";
import * as GetSecretProcedure from "../get_secret_procedure";
import * as ReplaceFileContentProcedure from "../replace_file_content_procedure";
import * as RequestDownloadUrlProcedure from "../request_download_url_procedure";
import * as RequestUploadUrlProcedure from "../request_upload_url_procedure";
import * as RevealSecretProcedure from "../reveal_secret_procedure";
import * as RevealSshKeyProcedure from "../reveal_ssh_key_procedure";
import * as SearchFilesProcedure from "../search_files_procedure";
import * as UpdateS3ConfigWithCredentialsProcedure from "../update_s_3_config_with_credentials_procedure";

export type ApiKeyHasPermissionArgs = __Infer<typeof ApiKeyHasPermissionProcedure.params>;
export type ApiKeyHasPermissionResult = __Infer<typeof ApiKeyHasPermissionProcedure.returnType>;
export type CreateApiKeyArgs = __Infer<typeof CreateApiKeyProcedure.params>;
export type CreateApiKeyResult = __Infer<typeof CreateApiKeyProcedure.returnType>;
export type GetFileArgs = __Infer<typeof GetFileProcedure.params>;
export type GetFileResult = __Infer<typeof GetFileProcedure.returnType>;
export type GetSecretArgs = __Infer<typeof GetSecretProcedure.params>;
export type GetSecretResult = __Infer<typeof GetSecretProcedure.returnType>;
export type ReplaceFileContentArgs = __Infer<typeof ReplaceFileContentProcedure.params>;
export type ReplaceFileContentResult = __Infer<typeof ReplaceFileContentProcedure.returnType>;
export type RequestDownloadUrlArgs = __Infer<typeof RequestDownloadUrlProcedure.params>;
export type RequestDownloadUrlResult = __Infer<typeof RequestDownloadUrlProcedure.returnType>;
export type RequestUploadUrlArgs = __Infer<typeof RequestUploadUrlProcedure.params>;
export type RequestUploadUrlResult = __Infer<typeof RequestUploadUrlProcedure.returnType>;
export type RevealSecretArgs = __Infer<typeof RevealSecretProcedure.params>;
export type RevealSecretResult = __Infer<typeof RevealSecretProcedure.returnType>;
export type RevealSshKeyArgs = __Infer<typeof RevealSshKeyProcedure.params>;
export type RevealSshKeyResult = __Infer<typeof RevealSshKeyProcedure.returnType>;
export type SearchFilesArgs = __Infer<typeof SearchFilesProcedure.params>;
export type SearchFilesResult = __Infer<typeof SearchFilesProcedure.returnType>;
export type UpdateS3ConfigWithCredentialsArgs = __Infer<typeof UpdateS3ConfigWithCredentialsProcedure.params>;
export type UpdateS3ConfigWithCredentialsResult = __Infer<typeof UpdateS3ConfigWithCredentialsProcedure.returnType>;

