// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckUiCommandReducer from "../ack_ui_command_reducer";
import CreateFolderReducer from "../create_folder_reducer";
import DeleteDeviceReducer from "../delete_device_reducer";
import DeleteFileReducer from "../delete_file_reducer";
import DeleteSecretReducer from "../delete_secret_reducer";
import DeleteSshEndpointReducer from "../delete_ssh_endpoint_reducer";
import DeleteSshKeyReducer from "../delete_ssh_key_reducer";
import FinalizeUploadReducer from "../finalize_upload_reducer";
import PruneDeviceMetricsReducer from "../prune_device_metrics_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import RegisterFileReducer from "../register_file_reducer";
import RenameDeviceReducer from "../rename_device_reducer";
import RenameFileReducer from "../rename_file_reducer";
import ReportDeviceMetricsReducer from "../report_device_metrics_reducer";
import RevokeApiKeyReducer from "../revoke_api_key_reducer";
import SendUiEventReducer from "../send_ui_event_reducer";
import SetDeviceHostnameReducer from "../set_device_hostname_reducer";
import SetSecretReducer from "../set_secret_reducer";
import SetSecretDevicesReducer from "../set_secret_devices_reducer";
import SetSecretPermissionsReducer from "../set_secret_permissions_reducer";
import SetSecretValueReducer from "../set_secret_value_reducer";
import SetSshEndpointReducer from "../set_ssh_endpoint_reducer";
import SetSshEndpointDevicesReducer from "../set_ssh_endpoint_devices_reducer";
import SetSshEndpointEnabledReducer from "../set_ssh_endpoint_enabled_reducer";
import SetSshEndpointTagsReducer from "../set_ssh_endpoint_tags_reducer";
import SetSshKeyReducer from "../set_ssh_key_reducer";
import SetSshKeyDevicesReducer from "../set_ssh_key_devices_reducer";
import SetSshKeyTagsReducer from "../set_ssh_key_tags_reducer";
import SetSshKeyValueReducer from "../set_ssh_key_value_reducer";
import SignInReducer from "../sign_in_reducer";
import SignOutReducer from "../sign_out_reducer";
import SignUpReducer from "../sign_up_reducer";
import TouchDeviceReducer from "../touch_device_reducer";
import UpdateApiKeyPermissionsReducer from "../update_api_key_permissions_reducer";
import UpdateEmailReducer from "../update_email_reducer";
import UpdatePasswordReducer from "../update_password_reducer";
import UpdateS3ConfigReducer from "../update_s_3_config_reducer";
import UpdateSshEndpointReducer from "../update_ssh_endpoint_reducer";

export type AckUiCommandParams = __Infer<typeof AckUiCommandReducer>;
export type CreateFolderParams = __Infer<typeof CreateFolderReducer>;
export type DeleteDeviceParams = __Infer<typeof DeleteDeviceReducer>;
export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type DeleteSecretParams = __Infer<typeof DeleteSecretReducer>;
export type DeleteSshEndpointParams = __Infer<typeof DeleteSshEndpointReducer>;
export type DeleteSshKeyParams = __Infer<typeof DeleteSshKeyReducer>;
export type FinalizeUploadParams = __Infer<typeof FinalizeUploadReducer>;
export type PruneDeviceMetricsParams = __Infer<typeof PruneDeviceMetricsReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type RegisterFileParams = __Infer<typeof RegisterFileReducer>;
export type RenameDeviceParams = __Infer<typeof RenameDeviceReducer>;
export type RenameFileParams = __Infer<typeof RenameFileReducer>;
export type ReportDeviceMetricsParams = __Infer<typeof ReportDeviceMetricsReducer>;
export type RevokeApiKeyParams = __Infer<typeof RevokeApiKeyReducer>;
export type SendUiEventParams = __Infer<typeof SendUiEventReducer>;
export type SetDeviceHostnameParams = __Infer<typeof SetDeviceHostnameReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type SetSecretDevicesParams = __Infer<typeof SetSecretDevicesReducer>;
export type SetSecretPermissionsParams = __Infer<typeof SetSecretPermissionsReducer>;
export type SetSecretValueParams = __Infer<typeof SetSecretValueReducer>;
export type SetSshEndpointParams = __Infer<typeof SetSshEndpointReducer>;
export type SetSshEndpointDevicesParams = __Infer<typeof SetSshEndpointDevicesReducer>;
export type SetSshEndpointEnabledParams = __Infer<typeof SetSshEndpointEnabledReducer>;
export type SetSshEndpointTagsParams = __Infer<typeof SetSshEndpointTagsReducer>;
export type SetSshKeyParams = __Infer<typeof SetSshKeyReducer>;
export type SetSshKeyDevicesParams = __Infer<typeof SetSshKeyDevicesReducer>;
export type SetSshKeyTagsParams = __Infer<typeof SetSshKeyTagsReducer>;
export type SetSshKeyValueParams = __Infer<typeof SetSshKeyValueReducer>;
export type SignInParams = __Infer<typeof SignInReducer>;
export type SignOutParams = __Infer<typeof SignOutReducer>;
export type SignUpParams = __Infer<typeof SignUpReducer>;
export type TouchDeviceParams = __Infer<typeof TouchDeviceReducer>;
export type UpdateApiKeyPermissionsParams = __Infer<typeof UpdateApiKeyPermissionsReducer>;
export type UpdateEmailParams = __Infer<typeof UpdateEmailReducer>;
export type UpdatePasswordParams = __Infer<typeof UpdatePasswordReducer>;
export type UpdateS3ConfigParams = __Infer<typeof UpdateS3ConfigReducer>;
export type UpdateSshEndpointParams = __Infer<typeof UpdateSshEndpointReducer>;

