// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DeleteConfigReducer from "../delete_config_reducer";
import DeleteDeviceReducer from "../delete_device_reducer";
import DeleteFileReducer from "../delete_file_reducer";
import DeleteSecretReducer from "../delete_secret_reducer";
import FinalizeUploadReducer from "../finalize_upload_reducer";
import RegisterDeviceReducer from "../register_device_reducer";
import RegisterFileReducer from "../register_file_reducer";
import RenameDeviceReducer from "../rename_device_reducer";
import RenameFileReducer from "../rename_file_reducer";
import RevokeApiKeyReducer from "../revoke_api_key_reducer";
import SetConfigReducer from "../set_config_reducer";
import SetDeviceHostnameReducer from "../set_device_hostname_reducer";
import SetSecretReducer from "../set_secret_reducer";
import SetSecretDevicesReducer from "../set_secret_devices_reducer";
import SetSecretPermissionsReducer from "../set_secret_permissions_reducer";
import SetSecretValueReducer from "../set_secret_value_reducer";
import SignInReducer from "../sign_in_reducer";
import SignUpReducer from "../sign_up_reducer";
import TouchDeviceReducer from "../touch_device_reducer";
import UpdateApiKeyPermissionsReducer from "../update_api_key_permissions_reducer";
import UpdateS3ConfigReducer from "../update_s_3_config_reducer";

export type DeleteConfigParams = __Infer<typeof DeleteConfigReducer>;
export type DeleteDeviceParams = __Infer<typeof DeleteDeviceReducer>;
export type DeleteFileParams = __Infer<typeof DeleteFileReducer>;
export type DeleteSecretParams = __Infer<typeof DeleteSecretReducer>;
export type FinalizeUploadParams = __Infer<typeof FinalizeUploadReducer>;
export type RegisterDeviceParams = __Infer<typeof RegisterDeviceReducer>;
export type RegisterFileParams = __Infer<typeof RegisterFileReducer>;
export type RenameDeviceParams = __Infer<typeof RenameDeviceReducer>;
export type RenameFileParams = __Infer<typeof RenameFileReducer>;
export type RevokeApiKeyParams = __Infer<typeof RevokeApiKeyReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type SetDeviceHostnameParams = __Infer<typeof SetDeviceHostnameReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type SetSecretDevicesParams = __Infer<typeof SetSecretDevicesReducer>;
export type SetSecretPermissionsParams = __Infer<typeof SetSecretPermissionsReducer>;
export type SetSecretValueParams = __Infer<typeof SetSecretValueReducer>;
export type SignInParams = __Infer<typeof SignInReducer>;
export type SignUpParams = __Infer<typeof SignUpReducer>;
export type TouchDeviceParams = __Infer<typeof TouchDeviceReducer>;
export type UpdateApiKeyPermissionsParams = __Infer<typeof UpdateApiKeyPermissionsReducer>;
export type UpdateS3ConfigParams = __Infer<typeof UpdateS3ConfigReducer>;

