// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AckUiCommandArgs {
    pub command_id: u64,
    pub device_id: u64,
}

impl From<AckUiCommandArgs> for super::Reducer {
    fn from(args: AckUiCommandArgs) -> Self {
        Self::AckUiCommand {
            command_id: args.command_id,
            device_id: args.device_id,
        }
    }
}

impl __sdk::InModule for AckUiCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ack_ui_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ack_ui_command {
    /// Request that the remote module invoke the reducer `ack_ui_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ack_ui_command:ack_ui_command_then`] to run a callback after the reducer completes.
    fn ack_ui_command(&self, command_id: u64, device_id: u64) -> __sdk::Result<()> {
        self.ack_ui_command_then(command_id, device_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ack_ui_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ack_ui_command_then(
        &self,
        command_id: u64,
        device_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ack_ui_command for super::RemoteReducers {
    fn ack_ui_command_then(
        &self,
        command_id: u64,
        device_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AckUiCommandArgs {
                command_id,
                device_id,
            },
            callback,
        )
    }
}
