// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ApiKeyHasPermissionArgs {
    pub token: String,
    pub permission: String,
}

impl __sdk::InModule for ApiKeyHasPermissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `api_key_has_permission`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait api_key_has_permission {
    fn api_key_has_permission(&self, token: String, permission: String) {
        self.api_key_has_permission_then(token, permission, |_, _| {});
    }

    fn api_key_has_permission_then(
        &self,
        token: String,
        permission: String,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<bool, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    );
}

impl api_key_has_permission for super::RemoteProcedures {
    fn api_key_has_permission_then(
        &self,
        token: String,
        permission: String,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<bool, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<bool, String>>(
                "api_key_has_permission",
                ApiKeyHasPermissionArgs { token, permission },
                __callback,
            );
    }
}
