// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApiKeyMetadata {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub permissions: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub last_used_at: Option<__sdk::Timestamp>,
    pub revoked_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ApiKeyMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApiKeyMetadata`.
///
/// Provides typed access to columns for query building.
pub struct ApiKeyMetadataCols {
    pub id: __sdk::__query_builder::Col<ApiKeyMetadata, u64>,
    pub owner: __sdk::__query_builder::Col<ApiKeyMetadata, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<ApiKeyMetadata, String>,
    pub permissions: __sdk::__query_builder::Col<ApiKeyMetadata, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<ApiKeyMetadata, __sdk::Timestamp>,
    pub last_used_at: __sdk::__query_builder::Col<ApiKeyMetadata, Option<__sdk::Timestamp>>,
    pub revoked_at: __sdk::__query_builder::Col<ApiKeyMetadata, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ApiKeyMetadata {
    type Cols = ApiKeyMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApiKeyMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            permissions: __sdk::__query_builder::Col::new(table_name, "permissions"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_used_at: __sdk::__query_builder::Col::new(table_name, "last_used_at"),
            revoked_at: __sdk::__query_builder::Col::new(table_name, "revoked_at"),
        }
    }
}
