// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AttachSshRelaySessionTokenArgs {
    pub session_id: u64,
    pub token: String,
}

impl From<AttachSshRelaySessionTokenArgs> for super::Reducer {
    fn from(args: AttachSshRelaySessionTokenArgs) -> Self {
        Self::AttachSshRelaySessionToken {
            session_id: args.session_id,
            token: args.token,
        }
    }
}

impl __sdk::InModule for AttachSshRelaySessionTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `attach_ssh_relay_session_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait attach_ssh_relay_session_token {
    /// Request that the remote module invoke the reducer `attach_ssh_relay_session_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`attach_ssh_relay_session_token:attach_ssh_relay_session_token_then`] to run a callback after the reducer completes.
    fn attach_ssh_relay_session_token(&self, session_id: u64, token: String) -> __sdk::Result<()> {
        self.attach_ssh_relay_session_token_then(session_id, token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `attach_ssh_relay_session_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn attach_ssh_relay_session_token_then(
        &self,
        session_id: u64,
        token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl attach_ssh_relay_session_token for super::RemoteReducers {
    fn attach_ssh_relay_session_token_then(
        &self,
        session_id: u64,
        token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AttachSshRelaySessionTokenArgs { session_id, token },
            callback,
        )
    }
}
