// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::created_api_key_type::CreatedApiKey;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct CreateApiKeyArgs {
    pub name: String,
    pub permissions: Vec<String>,
}

impl __sdk::InModule for CreateApiKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `create_api_key`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait create_api_key {
    fn create_api_key(&self, name: String, permissions: Vec<String>) {
        self.create_api_key_then(name, permissions, |_, _| {});
    }

    fn create_api_key_then(
        &self,
        name: String,
        permissions: Vec<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<CreatedApiKey, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl create_api_key for super::RemoteProcedures {
    fn create_api_key_then(
        &self,
        name: String,
        permissions: Vec<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<CreatedApiKey, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<CreatedApiKey, String>>(
                "create_api_key",
                CreateApiKeyArgs { name, permissions },
                __callback,
            );
    }
}
