// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeviceMetadata {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub hostname: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub last_seen_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for DeviceMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeviceMetadata`.
///
/// Provides typed access to columns for query building.
pub struct DeviceMetadataCols {
    pub id: __sdk::__query_builder::Col<DeviceMetadata, u64>,
    pub owner: __sdk::__query_builder::Col<DeviceMetadata, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<DeviceMetadata, String>,
    pub hostname: __sdk::__query_builder::Col<DeviceMetadata, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<DeviceMetadata, __sdk::Timestamp>,
    pub last_seen_at: __sdk::__query_builder::Col<DeviceMetadata, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for DeviceMetadata {
    type Cols = DeviceMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            hostname: __sdk::__query_builder::Col::new(table_name, "hostname"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
        }
    }
}
