// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeviceMetric {
    pub id: u64,
    pub device_id: u64,
    pub recorded_at: __sdk::Timestamp,
    pub cpu_percent: f32,
    pub ram_used_bytes: u64,
    pub ram_total_bytes: u64,
    pub swap_used_bytes: u64,
    pub swap_total_bytes: u64,
    pub net_rx_bytes: u64,
    pub net_tx_bytes: u64,
    pub storage_used_bytes: u64,
    pub storage_total_bytes: u64,
}

impl __sdk::InModule for DeviceMetric {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeviceMetric`.
///
/// Provides typed access to columns for query building.
pub struct DeviceMetricCols {
    pub id: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub device_id: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub recorded_at: __sdk::__query_builder::Col<DeviceMetric, __sdk::Timestamp>,
    pub cpu_percent: __sdk::__query_builder::Col<DeviceMetric, f32>,
    pub ram_used_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub ram_total_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub swap_used_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub swap_total_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub net_rx_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub net_tx_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub storage_used_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
    pub storage_total_bytes: __sdk::__query_builder::Col<DeviceMetric, u64>,
}

impl __sdk::__query_builder::HasCols for DeviceMetric {
    type Cols = DeviceMetricCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceMetricCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
            cpu_percent: __sdk::__query_builder::Col::new(table_name, "cpu_percent"),
            ram_used_bytes: __sdk::__query_builder::Col::new(table_name, "ram_used_bytes"),
            ram_total_bytes: __sdk::__query_builder::Col::new(table_name, "ram_total_bytes"),
            swap_used_bytes: __sdk::__query_builder::Col::new(table_name, "swap_used_bytes"),
            swap_total_bytes: __sdk::__query_builder::Col::new(table_name, "swap_total_bytes"),
            net_rx_bytes: __sdk::__query_builder::Col::new(table_name, "net_rx_bytes"),
            net_tx_bytes: __sdk::__query_builder::Col::new(table_name, "net_tx_bytes"),
            storage_used_bytes: __sdk::__query_builder::Col::new(table_name, "storage_used_bytes"),
            storage_total_bytes: __sdk::__query_builder::Col::new(
                table_name,
                "storage_total_bytes",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `DeviceMetric`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeviceMetricIxCols {
    pub device_id: __sdk::__query_builder::IxCol<DeviceMetric, u64>,
    pub id: __sdk::__query_builder::IxCol<DeviceMetric, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeviceMetric {
    type IxCols = DeviceMetricIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeviceMetricIxCols {
            device_id: __sdk::__query_builder::IxCol::new(table_name, "device_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DeviceMetric {}
