// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Device {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub hostname: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub last_seen_at: Option<__sdk::Timestamp>,
    pub metrics_retention: Option<__sdk::TimeDuration>,
}

impl __sdk::InModule for Device {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Device`.
///
/// Provides typed access to columns for query building.
pub struct DeviceCols {
    pub id: __sdk::__query_builder::Col<Device, u64>,
    pub owner: __sdk::__query_builder::Col<Device, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Device, String>,
    pub hostname: __sdk::__query_builder::Col<Device, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Device, __sdk::Timestamp>,
    pub last_seen_at: __sdk::__query_builder::Col<Device, Option<__sdk::Timestamp>>,
    pub metrics_retention: __sdk::__query_builder::Col<Device, Option<__sdk::TimeDuration>>,
}

impl __sdk::__query_builder::HasCols for Device {
    type Cols = DeviceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            hostname: __sdk::__query_builder::Col::new(table_name, "hostname"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_seen_at: __sdk::__query_builder::Col::new(table_name, "last_seen_at"),
            metrics_retention: __sdk::__query_builder::Col::new(table_name, "metrics_retention"),
        }
    }
}

/// Indexed column accessor struct for the table `Device`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeviceIxCols {
    pub id: __sdk::__query_builder::IxCol<Device, u64>,
    pub owner: __sdk::__query_builder::IxCol<Device, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Device {
    type IxCols = DeviceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeviceIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Device {}
