// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeviceMetricSample {
    pub id: u64,
    pub device_id: u64,
    pub recorded_at: __sdk::Timestamp,
    pub cpu_percent: f32,
    pub ram_used_bytes: u64,
    pub ram_total_bytes: u64,
    pub swap_used_bytes: u64,
    pub swap_total_bytes: u64,
    pub net_rx_bytes: u64,
    pub net_tx_bytes: u64,
    pub storage_sync_root_used_bytes: u64,
    pub storage_sync_root_total_bytes: u64,
    pub storage_system_used_bytes: u64,
    pub storage_system_total_bytes: u64,
    pub sync_root_path: String,
}

impl __sdk::InModule for DeviceMetricSample {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeviceMetricSample`.
///
/// Provides typed access to columns for query building.
pub struct DeviceMetricSampleCols {
    pub id: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub device_id: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub recorded_at: __sdk::__query_builder::Col<DeviceMetricSample, __sdk::Timestamp>,
    pub cpu_percent: __sdk::__query_builder::Col<DeviceMetricSample, f32>,
    pub ram_used_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub ram_total_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub swap_used_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub swap_total_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub net_rx_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub net_tx_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub storage_sync_root_used_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub storage_sync_root_total_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub storage_system_used_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub storage_system_total_bytes: __sdk::__query_builder::Col<DeviceMetricSample, u64>,
    pub sync_root_path: __sdk::__query_builder::Col<DeviceMetricSample, String>,
}

impl __sdk::__query_builder::HasCols for DeviceMetricSample {
    type Cols = DeviceMetricSampleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceMetricSampleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
            cpu_percent: __sdk::__query_builder::Col::new(table_name, "cpu_percent"),
            ram_used_bytes: __sdk::__query_builder::Col::new(table_name, "ram_used_bytes"),
            ram_total_bytes: __sdk::__query_builder::Col::new(table_name, "ram_total_bytes"),
            swap_used_bytes: __sdk::__query_builder::Col::new(table_name, "swap_used_bytes"),
            swap_total_bytes: __sdk::__query_builder::Col::new(table_name, "swap_total_bytes"),
            net_rx_bytes: __sdk::__query_builder::Col::new(table_name, "net_rx_bytes"),
            net_tx_bytes: __sdk::__query_builder::Col::new(table_name, "net_tx_bytes"),
            storage_sync_root_used_bytes: __sdk::__query_builder::Col::new(
                table_name,
                "storage_sync_root_used_bytes",
            ),
            storage_sync_root_total_bytes: __sdk::__query_builder::Col::new(
                table_name,
                "storage_sync_root_total_bytes",
            ),
            storage_system_used_bytes: __sdk::__query_builder::Col::new(
                table_name,
                "storage_system_used_bytes",
            ),
            storage_system_total_bytes: __sdk::__query_builder::Col::new(
                table_name,
                "storage_system_total_bytes",
            ),
            sync_root_path: __sdk::__query_builder::Col::new(table_name, "sync_root_path"),
        }
    }
}
