// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FileMetadata {
    pub id: u64,
    pub name: String,
    pub tree_path: Option<String>,
    pub local_path: Option<String>,
    pub hash: String,
    pub size_bytes: u64,
    pub content_type: Option<String>,
    pub is_directory: bool,
    pub s_3_key: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for FileMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FileMetadata`.
///
/// Provides typed access to columns for query building.
pub struct FileMetadataCols {
    pub id: __sdk::__query_builder::Col<FileMetadata, u64>,
    pub name: __sdk::__query_builder::Col<FileMetadata, String>,
    pub tree_path: __sdk::__query_builder::Col<FileMetadata, Option<String>>,
    pub local_path: __sdk::__query_builder::Col<FileMetadata, Option<String>>,
    pub hash: __sdk::__query_builder::Col<FileMetadata, String>,
    pub size_bytes: __sdk::__query_builder::Col<FileMetadata, u64>,
    pub content_type: __sdk::__query_builder::Col<FileMetadata, Option<String>>,
    pub is_directory: __sdk::__query_builder::Col<FileMetadata, bool>,
    pub s_3_key: __sdk::__query_builder::Col<FileMetadata, String>,
    pub created_at: __sdk::__query_builder::Col<FileMetadata, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<FileMetadata, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for FileMetadata {
    type Cols = FileMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FileMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            tree_path: __sdk::__query_builder::Col::new(table_name, "tree_path"),
            local_path: __sdk::__query_builder::Col::new(table_name, "local_path"),
            hash: __sdk::__query_builder::Col::new(table_name, "hash"),
            size_bytes: __sdk::__query_builder::Col::new(table_name, "size_bytes"),
            content_type: __sdk::__query_builder::Col::new(table_name, "content_type"),
            is_directory: __sdk::__query_builder::Col::new(table_name, "is_directory"),
            s_3_key: __sdk::__query_builder::Col::new(table_name, "s_3_key"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
