// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FinalizeUploadArgs {
    pub file_id: u64,
    pub hash: String,
    pub size_bytes: u64,
}

impl From<FinalizeUploadArgs> for super::Reducer {
    fn from(args: FinalizeUploadArgs) -> Self {
        Self::FinalizeUpload {
            file_id: args.file_id,
            hash: args.hash,
            size_bytes: args.size_bytes,
        }
    }
}

impl __sdk::InModule for FinalizeUploadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `finalize_upload`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait finalize_upload {
    /// Request that the remote module invoke the reducer `finalize_upload` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`finalize_upload:finalize_upload_then`] to run a callback after the reducer completes.
    fn finalize_upload(&self, file_id: u64, hash: String, size_bytes: u64) -> __sdk::Result<()> {
        self.finalize_upload_then(file_id, hash, size_bytes, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `finalize_upload` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn finalize_upload_then(
        &self,
        file_id: u64,
        hash: String,
        size_bytes: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl finalize_upload for super::RemoteReducers {
    fn finalize_upload_then(
        &self,
        file_id: u64,
        hash: String,
        size_bytes: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            FinalizeUploadArgs {
                file_id,
                hash,
                size_bytes,
            },
            callback,
        )
    }
}
