// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::secret_metadata_type::SecretMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetSecretArgs {
    pub id: u64,
}

impl __sdk::InModule for GetSecretArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_secret`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_secret {
    fn get_secret(&self, id: u64) {
        self.get_secret_then(id, |_, _| {});
    }

    fn get_secret_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<Option<SecretMetadata>, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    );
}

impl get_secret for super::RemoteProcedures {
    fn get_secret_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<Option<SecretMetadata>, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Option<SecretMetadata>, String>>(
                "get_secret",
                GetSecretArgs { id },
                __callback,
            );
    }
}
