// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::file_metadata_type::FileMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct GetFileArgs {
    pub file_id: u64,
}

impl __sdk::InModule for GetFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `get_file`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait get_file {
    fn get_file(&self, file_id: u64) {
        self.get_file_then(file_id, |_, _| {});
    }

    fn get_file_then(
        &self,
        file_id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Option<FileMetadata>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl get_file for super::RemoteProcedures {
    fn get_file_then(
        &self,
        file_id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Option<FileMetadata>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Option<FileMetadata>, String>>(
                "get_file",
                GetFileArgs { file_id },
                __callback,
            );
    }
}
