//! Auto-generated SpacetimeDB client bindings for the `spacenix` module.
//!
//! Regenerate with `./scripts/gen-bindings.sh`.
//!
//! The body of this file is produced by `spacetime generate`. The header
//! comment above is the only line maintained by hand.

#![allow(unused, clippy::all, non_camel_case_types, non_snake_case)]

// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod ack_ui_command_reducer;
pub mod api_key_has_permission_procedure;
pub mod api_key_metadata_type;
pub mod api_key_type;
pub mod create_api_key_procedure;
pub mod create_folder_reducer;
pub mod created_api_key_type;
pub mod delete_device_reducer;
pub mod delete_file_reducer;
pub mod delete_secret_reducer;
pub mod delete_ssh_endpoint_reducer;
pub mod delete_ssh_key_reducer;
pub mod device_metadata_type;
pub mod device_metric_sample_type;
pub mod device_metric_type;
pub mod device_metrics_report_type;
pub mod device_type;
pub mod file_metadata_type;
pub mod finalize_upload_reducer;
pub mod get_file_procedure;
pub mod get_secret_procedure;
pub mod my_api_keys_table;
pub mod my_device_metrics_table;
pub mod my_devices_table;
pub mod my_files_table;
pub mod my_secrets_table;
pub mod my_ssh_endpoints_table;
pub mod my_ssh_keys_table;
pub mod my_ui_commands_table;
pub mod my_user_table;
pub mod password_credential_type;
pub mod person_type;
pub mod prune_device_metrics_reducer;
pub mod register_device_reducer;
pub mod register_file_reducer;
pub mod rename_device_reducer;
pub mod rename_file_reducer;
pub mod replace_file_content_procedure;
pub mod replace_ticket_type;
pub mod report_device_metrics_reducer;
pub mod request_download_url_procedure;
pub mod request_upload_url_procedure;
pub mod reveal_secret_procedure;
pub mod reveal_ssh_key_procedure;
pub mod revoke_api_key_reducer;
pub mod s_3_config_status_table;
pub mod s_3_config_status_type;
pub mod s_3_config_type;
pub mod search_files_procedure;
pub mod secret_metadata_type;
pub mod secret_value_type;
pub mod send_ui_event_reducer;
pub mod session_type;
pub mod set_device_hostname_reducer;
pub mod set_device_metrics_retention_reducer;
pub mod set_secret_devices_reducer;
pub mod set_secret_permissions_reducer;
pub mod set_secret_reducer;
pub mod set_secret_value_reducer;
pub mod set_ssh_endpoint_devices_reducer;
pub mod set_ssh_endpoint_enabled_reducer;
pub mod set_ssh_endpoint_reducer;
pub mod set_ssh_endpoint_tags_reducer;
pub mod set_ssh_key_devices_reducer;
pub mod set_ssh_key_reducer;
pub mod set_ssh_key_tags_reducer;
pub mod set_ssh_key_value_reducer;
pub mod sign_in_reducer;
pub mod sign_out_reducer;
pub mod sign_up_reducer;
pub mod ssh_endpoint_metadata_type;
pub mod ssh_endpoint_type;
pub mod ssh_key_metadata_type;
pub mod ssh_key_type;
pub mod ssh_key_value_type;
pub mod touch_device_reducer;
pub mod ui_command_metadata_type;
pub mod ui_command_table;
pub mod ui_command_type;
pub mod ui_event_table;
pub mod ui_event_type;
pub mod update_api_key_permissions_reducer;
pub mod update_email_reducer;
pub mod update_password_reducer;
pub mod update_s_3_config_reducer;
pub mod update_s_3_config_with_credentials_procedure;
pub mod update_ssh_endpoint_reducer;
pub mod upload_ticket_type;
pub mod user_file_type;
pub mod user_profile_type;
pub mod user_secret_type;
pub mod user_type;

pub use ack_ui_command_reducer::ack_ui_command;
pub use api_key_has_permission_procedure::api_key_has_permission;
pub use api_key_metadata_type::ApiKeyMetadata;
pub use api_key_type::ApiKey;
pub use create_api_key_procedure::create_api_key;
pub use create_folder_reducer::create_folder;
pub use created_api_key_type::CreatedApiKey;
pub use delete_device_reducer::delete_device;
pub use delete_file_reducer::delete_file;
pub use delete_secret_reducer::delete_secret;
pub use delete_ssh_endpoint_reducer::delete_ssh_endpoint;
pub use delete_ssh_key_reducer::delete_ssh_key;
pub use device_metadata_type::DeviceMetadata;
pub use device_metric_sample_type::DeviceMetricSample;
pub use device_metric_type::DeviceMetric;
pub use device_metrics_report_type::DeviceMetricsReport;
pub use device_type::Device;
pub use file_metadata_type::FileMetadata;
pub use finalize_upload_reducer::finalize_upload;
pub use get_file_procedure::get_file;
pub use get_secret_procedure::get_secret;
pub use my_api_keys_table::*;
pub use my_device_metrics_table::*;
pub use my_devices_table::*;
pub use my_files_table::*;
pub use my_secrets_table::*;
pub use my_ssh_endpoints_table::*;
pub use my_ssh_keys_table::*;
pub use my_ui_commands_table::*;
pub use my_user_table::*;
pub use password_credential_type::PasswordCredential;
pub use person_type::Person;
pub use prune_device_metrics_reducer::prune_device_metrics;
pub use register_device_reducer::register_device;
pub use register_file_reducer::register_file;
pub use rename_device_reducer::rename_device;
pub use rename_file_reducer::rename_file;
pub use replace_file_content_procedure::replace_file_content;
pub use replace_ticket_type::ReplaceTicket;
pub use report_device_metrics_reducer::report_device_metrics;
pub use request_download_url_procedure::request_download_url;
pub use request_upload_url_procedure::request_upload_url;
pub use reveal_secret_procedure::reveal_secret;
pub use reveal_ssh_key_procedure::reveal_ssh_key;
pub use revoke_api_key_reducer::revoke_api_key;
pub use s_3_config_status_table::*;
pub use s_3_config_status_type::S3ConfigStatus;
pub use s_3_config_type::S3Config;
pub use search_files_procedure::search_files;
pub use secret_metadata_type::SecretMetadata;
pub use secret_value_type::SecretValue;
pub use send_ui_event_reducer::send_ui_event;
pub use session_type::Session;
pub use set_device_hostname_reducer::set_device_hostname;
pub use set_device_metrics_retention_reducer::set_device_metrics_retention;
pub use set_secret_devices_reducer::set_secret_devices;
pub use set_secret_permissions_reducer::set_secret_permissions;
pub use set_secret_reducer::set_secret;
pub use set_secret_value_reducer::set_secret_value;
pub use set_ssh_endpoint_devices_reducer::set_ssh_endpoint_devices;
pub use set_ssh_endpoint_enabled_reducer::set_ssh_endpoint_enabled;
pub use set_ssh_endpoint_reducer::set_ssh_endpoint;
pub use set_ssh_endpoint_tags_reducer::set_ssh_endpoint_tags;
pub use set_ssh_key_devices_reducer::set_ssh_key_devices;
pub use set_ssh_key_reducer::set_ssh_key;
pub use set_ssh_key_tags_reducer::set_ssh_key_tags;
pub use set_ssh_key_value_reducer::set_ssh_key_value;
pub use sign_in_reducer::sign_in;
pub use sign_out_reducer::sign_out;
pub use sign_up_reducer::sign_up;
pub use ssh_endpoint_metadata_type::SshEndpointMetadata;
pub use ssh_endpoint_type::SshEndpoint;
pub use ssh_key_metadata_type::SshKeyMetadata;
pub use ssh_key_type::SshKey;
pub use ssh_key_value_type::SshKeyValue;
pub use touch_device_reducer::touch_device;
pub use ui_command_metadata_type::UiCommandMetadata;
pub use ui_command_table::*;
pub use ui_command_type::UiCommand;
pub use ui_event_table::*;
pub use ui_event_type::UiEvent;
pub use update_api_key_permissions_reducer::update_api_key_permissions;
pub use update_email_reducer::update_email;
pub use update_password_reducer::update_password;
pub use update_s_3_config_reducer::update_s_3_config;
pub use update_s_3_config_with_credentials_procedure::update_s_3_config_with_credentials;
pub use update_ssh_endpoint_reducer::update_ssh_endpoint;
pub use upload_ticket_type::UploadTicket;
pub use user_file_type::UserFile;
pub use user_profile_type::UserProfile;
pub use user_secret_type::UserSecret;
pub use user_type::User;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AckUiCommand {
        command_id: u64,
        device_id: u64,
    },
    CreateFolder {
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
    },
    DeleteDevice {
        device_id: u64,
    },
    DeleteFile {
        file_id: u64,
    },
    DeleteSecret {
        id: u64,
    },
    DeleteSshEndpoint {
        id: u64,
    },
    DeleteSshKey {
        id: u64,
    },
    FinalizeUpload {
        file_id: u64,
        hash: String,
        size_bytes: u64,
    },
    PruneDeviceMetrics {
        device_id: u64,
        older_than: __sdk::Timestamp,
    },
    RegisterDevice {
        name: String,
        hostname: Option<String>,
    },
    RegisterFile {
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        hash: String,
        size_bytes: u64,
        content_type: Option<String>,
    },
    RenameDevice {
        device_id: u64,
        name: String,
    },
    RenameFile {
        file_id: u64,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
    },
    ReportDeviceMetrics {
        device_id: u64,
        report: DeviceMetricsReport,
    },
    RevokeApiKey {
        api_key_id: u64,
    },
    SendUiEvent {
        target_device_id: Option<u64>,
        kind: String,
        payload_json: String,
    },
    SetDeviceHostname {
        device_id: u64,
        hostname: Option<String>,
    },
    SetDeviceMetricsRetention {
        device_id: u64,
        retention_secs: u64,
    },
    SetSecret {
        env: String,
        value: String,
        device_ids: Vec<String>,
        permissions: Vec<String>,
    },
    SetSecretDevices {
        id: u64,
        device_ids: Vec<String>,
    },
    SetSecretPermissions {
        id: u64,
        permissions: Vec<String>,
    },
    SetSecretValue {
        id: u64,
        value: String,
    },
    SetSshEndpoint {
        name: String,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
        device_ids: Vec<String>,
        tags: Vec<String>,
        enabled: bool,
    },
    SetSshEndpointDevices {
        id: u64,
        device_ids: Vec<String>,
    },
    SetSshEndpointEnabled {
        id: u64,
        enabled: bool,
    },
    SetSshEndpointTags {
        id: u64,
        tags: Vec<String>,
    },
    SetSshKey {
        name: String,
        public_key: String,
        private_key: String,
        device_ids: Vec<String>,
        tags: Vec<String>,
    },
    SetSshKeyDevices {
        id: u64,
        device_ids: Vec<String>,
    },
    SetSshKeyTags {
        id: u64,
        tags: Vec<String>,
    },
    SetSshKeyValue {
        id: u64,
        public_key: String,
        private_key: String,
    },
    SignIn {
        email: String,
        password: String,
    },
    SignOut,
    SignUp {
        email: String,
        password: String,
        display_name: Option<String>,
    },
    TouchDevice {
        device_id: u64,
    },
    UpdateApiKeyPermissions {
        api_key_id: u64,
        permissions: Vec<String>,
    },
    UpdateEmail {
        new_email: String,
        current_password: String,
    },
    UpdatePassword {
        current_password: String,
        new_password: String,
    },
    UpdateS3Config {
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,
    },
    UpdateSshEndpoint {
        id: u64,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AckUiCommand { .. } => "ack_ui_command",
            Reducer::CreateFolder { .. } => "create_folder",
            Reducer::DeleteDevice { .. } => "delete_device",
            Reducer::DeleteFile { .. } => "delete_file",
            Reducer::DeleteSecret { .. } => "delete_secret",
            Reducer::DeleteSshEndpoint { .. } => "delete_ssh_endpoint",
            Reducer::DeleteSshKey { .. } => "delete_ssh_key",
            Reducer::FinalizeUpload { .. } => "finalize_upload",
            Reducer::PruneDeviceMetrics { .. } => "prune_device_metrics",
            Reducer::RegisterDevice { .. } => "register_device",
            Reducer::RegisterFile { .. } => "register_file",
            Reducer::RenameDevice { .. } => "rename_device",
            Reducer::RenameFile { .. } => "rename_file",
            Reducer::ReportDeviceMetrics { .. } => "report_device_metrics",
            Reducer::RevokeApiKey { .. } => "revoke_api_key",
            Reducer::SendUiEvent { .. } => "send_ui_event",
            Reducer::SetDeviceHostname { .. } => "set_device_hostname",
            Reducer::SetDeviceMetricsRetention { .. } => "set_device_metrics_retention",
            Reducer::SetSecret { .. } => "set_secret",
            Reducer::SetSecretDevices { .. } => "set_secret_devices",
            Reducer::SetSecretPermissions { .. } => "set_secret_permissions",
            Reducer::SetSecretValue { .. } => "set_secret_value",
            Reducer::SetSshEndpoint { .. } => "set_ssh_endpoint",
            Reducer::SetSshEndpointDevices { .. } => "set_ssh_endpoint_devices",
            Reducer::SetSshEndpointEnabled { .. } => "set_ssh_endpoint_enabled",
            Reducer::SetSshEndpointTags { .. } => "set_ssh_endpoint_tags",
            Reducer::SetSshKey { .. } => "set_ssh_key",
            Reducer::SetSshKeyDevices { .. } => "set_ssh_key_devices",
            Reducer::SetSshKeyTags { .. } => "set_ssh_key_tags",
            Reducer::SetSshKeyValue { .. } => "set_ssh_key_value",
            Reducer::SignIn { .. } => "sign_in",
            Reducer::SignOut => "sign_out",
            Reducer::SignUp { .. } => "sign_up",
            Reducer::TouchDevice { .. } => "touch_device",
            Reducer::UpdateApiKeyPermissions { .. } => "update_api_key_permissions",
            Reducer::UpdateEmail { .. } => "update_email",
            Reducer::UpdatePassword { .. } => "update_password",
            Reducer::UpdateS3Config { .. } => "update_s_3_config",
            Reducer::UpdateSshEndpoint { .. } => "update_ssh_endpoint",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AckUiCommand {
                command_id,
                device_id,
            } => __sats::bsatn::to_vec(&ack_ui_command_reducer::AckUiCommandArgs {
                command_id: command_id.clone(),
                device_id: device_id.clone(),
            }),
            Reducer::CreateFolder {
                name,
                tree_path,
                local_path,
            } => __sats::bsatn::to_vec(&create_folder_reducer::CreateFolderArgs {
                name: name.clone(),
                tree_path: tree_path.clone(),
                local_path: local_path.clone(),
            }),
            Reducer::DeleteDevice { device_id } => {
                __sats::bsatn::to_vec(&delete_device_reducer::DeleteDeviceArgs {
                    device_id: device_id.clone(),
                })
            }
            Reducer::DeleteFile { file_id } => {
                __sats::bsatn::to_vec(&delete_file_reducer::DeleteFileArgs {
                    file_id: file_id.clone(),
                })
            }
            Reducer::DeleteSecret { id } => {
                __sats::bsatn::to_vec(&delete_secret_reducer::DeleteSecretArgs { id: id.clone() })
            }
            Reducer::DeleteSshEndpoint { id } => {
                __sats::bsatn::to_vec(&delete_ssh_endpoint_reducer::DeleteSshEndpointArgs {
                    id: id.clone(),
                })
            }
            Reducer::DeleteSshKey { id } => {
                __sats::bsatn::to_vec(&delete_ssh_key_reducer::DeleteSshKeyArgs { id: id.clone() })
            }
            Reducer::FinalizeUpload {
                file_id,
                hash,
                size_bytes,
            } => __sats::bsatn::to_vec(&finalize_upload_reducer::FinalizeUploadArgs {
                file_id: file_id.clone(),
                hash: hash.clone(),
                size_bytes: size_bytes.clone(),
            }),
            Reducer::PruneDeviceMetrics {
                device_id,
                older_than,
            } => __sats::bsatn::to_vec(&prune_device_metrics_reducer::PruneDeviceMetricsArgs {
                device_id: device_id.clone(),
                older_than: older_than.clone(),
            }),
            Reducer::RegisterDevice { name, hostname } => {
                __sats::bsatn::to_vec(&register_device_reducer::RegisterDeviceArgs {
                    name: name.clone(),
                    hostname: hostname.clone(),
                })
            }
            Reducer::RegisterFile {
                name,
                tree_path,
                local_path,
                hash,
                size_bytes,
                content_type,
            } => __sats::bsatn::to_vec(&register_file_reducer::RegisterFileArgs {
                name: name.clone(),
                tree_path: tree_path.clone(),
                local_path: local_path.clone(),
                hash: hash.clone(),
                size_bytes: size_bytes.clone(),
                content_type: content_type.clone(),
            }),
            Reducer::RenameDevice { device_id, name } => {
                __sats::bsatn::to_vec(&rename_device_reducer::RenameDeviceArgs {
                    device_id: device_id.clone(),
                    name: name.clone(),
                })
            }
            Reducer::RenameFile {
                file_id,
                name,
                tree_path,
                local_path,
            } => __sats::bsatn::to_vec(&rename_file_reducer::RenameFileArgs {
                file_id: file_id.clone(),
                name: name.clone(),
                tree_path: tree_path.clone(),
                local_path: local_path.clone(),
            }),
            Reducer::ReportDeviceMetrics { device_id, report } => {
                __sats::bsatn::to_vec(&report_device_metrics_reducer::ReportDeviceMetricsArgs {
                    device_id: device_id.clone(),
                    report: report.clone(),
                })
            }
            Reducer::RevokeApiKey { api_key_id } => {
                __sats::bsatn::to_vec(&revoke_api_key_reducer::RevokeApiKeyArgs {
                    api_key_id: api_key_id.clone(),
                })
            }
            Reducer::SendUiEvent {
                target_device_id,
                kind,
                payload_json,
            } => __sats::bsatn::to_vec(&send_ui_event_reducer::SendUiEventArgs {
                target_device_id: target_device_id.clone(),
                kind: kind.clone(),
                payload_json: payload_json.clone(),
            }),
            Reducer::SetDeviceHostname {
                device_id,
                hostname,
            } => __sats::bsatn::to_vec(&set_device_hostname_reducer::SetDeviceHostnameArgs {
                device_id: device_id.clone(),
                hostname: hostname.clone(),
            }),
            Reducer::SetDeviceMetricsRetention {
                device_id,
                retention_secs,
            } => __sats::bsatn::to_vec(
                &set_device_metrics_retention_reducer::SetDeviceMetricsRetentionArgs {
                    device_id: device_id.clone(),
                    retention_secs: retention_secs.clone(),
                },
            ),
            Reducer::SetSecret {
                env,
                value,
                device_ids,
                permissions,
            } => __sats::bsatn::to_vec(&set_secret_reducer::SetSecretArgs {
                env: env.clone(),
                value: value.clone(),
                device_ids: device_ids.clone(),
                permissions: permissions.clone(),
            }),
            Reducer::SetSecretDevices { id, device_ids } => {
                __sats::bsatn::to_vec(&set_secret_devices_reducer::SetSecretDevicesArgs {
                    id: id.clone(),
                    device_ids: device_ids.clone(),
                })
            }
            Reducer::SetSecretPermissions { id, permissions } => {
                __sats::bsatn::to_vec(&set_secret_permissions_reducer::SetSecretPermissionsArgs {
                    id: id.clone(),
                    permissions: permissions.clone(),
                })
            }
            Reducer::SetSecretValue { id, value } => {
                __sats::bsatn::to_vec(&set_secret_value_reducer::SetSecretValueArgs {
                    id: id.clone(),
                    value: value.clone(),
                })
            }
            Reducer::SetSshEndpoint {
                name,
                host,
                port,
                username,
                key_id,
                device_ids,
                tags,
                enabled,
            } => __sats::bsatn::to_vec(&set_ssh_endpoint_reducer::SetSshEndpointArgs {
                name: name.clone(),
                host: host.clone(),
                port: port.clone(),
                username: username.clone(),
                key_id: key_id.clone(),
                device_ids: device_ids.clone(),
                tags: tags.clone(),
                enabled: enabled.clone(),
            }),
            Reducer::SetSshEndpointDevices { id, device_ids } => __sats::bsatn::to_vec(
                &set_ssh_endpoint_devices_reducer::SetSshEndpointDevicesArgs {
                    id: id.clone(),
                    device_ids: device_ids.clone(),
                },
            ),
            Reducer::SetSshEndpointEnabled { id, enabled } => __sats::bsatn::to_vec(
                &set_ssh_endpoint_enabled_reducer::SetSshEndpointEnabledArgs {
                    id: id.clone(),
                    enabled: enabled.clone(),
                },
            ),
            Reducer::SetSshEndpointTags { id, tags } => {
                __sats::bsatn::to_vec(&set_ssh_endpoint_tags_reducer::SetSshEndpointTagsArgs {
                    id: id.clone(),
                    tags: tags.clone(),
                })
            }
            Reducer::SetSshKey {
                name,
                public_key,
                private_key,
                device_ids,
                tags,
            } => __sats::bsatn::to_vec(&set_ssh_key_reducer::SetSshKeyArgs {
                name: name.clone(),
                public_key: public_key.clone(),
                private_key: private_key.clone(),
                device_ids: device_ids.clone(),
                tags: tags.clone(),
            }),
            Reducer::SetSshKeyDevices { id, device_ids } => {
                __sats::bsatn::to_vec(&set_ssh_key_devices_reducer::SetSshKeyDevicesArgs {
                    id: id.clone(),
                    device_ids: device_ids.clone(),
                })
            }
            Reducer::SetSshKeyTags { id, tags } => {
                __sats::bsatn::to_vec(&set_ssh_key_tags_reducer::SetSshKeyTagsArgs {
                    id: id.clone(),
                    tags: tags.clone(),
                })
            }
            Reducer::SetSshKeyValue {
                id,
                public_key,
                private_key,
            } => __sats::bsatn::to_vec(&set_ssh_key_value_reducer::SetSshKeyValueArgs {
                id: id.clone(),
                public_key: public_key.clone(),
                private_key: private_key.clone(),
            }),
            Reducer::SignIn { email, password } => {
                __sats::bsatn::to_vec(&sign_in_reducer::SignInArgs {
                    email: email.clone(),
                    password: password.clone(),
                })
            }
            Reducer::SignOut => __sats::bsatn::to_vec(&sign_out_reducer::SignOutArgs {}),
            Reducer::SignUp {
                email,
                password,
                display_name,
            } => __sats::bsatn::to_vec(&sign_up_reducer::SignUpArgs {
                email: email.clone(),
                password: password.clone(),
                display_name: display_name.clone(),
            }),
            Reducer::TouchDevice { device_id } => {
                __sats::bsatn::to_vec(&touch_device_reducer::TouchDeviceArgs {
                    device_id: device_id.clone(),
                })
            }
            Reducer::UpdateApiKeyPermissions {
                api_key_id,
                permissions,
            } => __sats::bsatn::to_vec(
                &update_api_key_permissions_reducer::UpdateApiKeyPermissionsArgs {
                    api_key_id: api_key_id.clone(),
                    permissions: permissions.clone(),
                },
            ),
            Reducer::UpdateEmail {
                new_email,
                current_password,
            } => __sats::bsatn::to_vec(&update_email_reducer::UpdateEmailArgs {
                new_email: new_email.clone(),
                current_password: current_password.clone(),
            }),
            Reducer::UpdatePassword {
                current_password,
                new_password,
            } => __sats::bsatn::to_vec(&update_password_reducer::UpdatePasswordArgs {
                current_password: current_password.clone(),
                new_password: new_password.clone(),
            }),
            Reducer::UpdateS3Config {
                bucket,
                region,
                endpoint,
                access_key_id,
                secret_access_key,
                path_prefix,
                public_base_url,
            } => __sats::bsatn::to_vec(&update_s_3_config_reducer::UpdateS3ConfigArgs {
                bucket: bucket.clone(),
                region: region.clone(),
                endpoint: endpoint.clone(),
                access_key_id: access_key_id.clone(),
                secret_access_key: secret_access_key.clone(),
                path_prefix: path_prefix.clone(),
                public_base_url: public_base_url.clone(),
            }),
            Reducer::UpdateSshEndpoint {
                id,
                host,
                port,
                username,
                key_id,
            } => __sats::bsatn::to_vec(&update_ssh_endpoint_reducer::UpdateSshEndpointArgs {
                id: id.clone(),
                host: host.clone(),
                port: port.clone(),
                username: username.clone(),
                key_id: key_id.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    my_api_keys: __sdk::TableUpdate<ApiKeyMetadata>,
    my_device_metrics: __sdk::TableUpdate<DeviceMetricSample>,
    my_devices: __sdk::TableUpdate<DeviceMetadata>,
    my_files: __sdk::TableUpdate<FileMetadata>,
    my_secrets: __sdk::TableUpdate<SecretMetadata>,
    my_ssh_endpoints: __sdk::TableUpdate<SshEndpointMetadata>,
    my_ssh_keys: __sdk::TableUpdate<SshKeyMetadata>,
    my_ui_commands: __sdk::TableUpdate<UiCommandMetadata>,
    my_user: __sdk::TableUpdate<UserProfile>,
    s_3_config_status: __sdk::TableUpdate<S3ConfigStatus>,
    ui_command: __sdk::TableUpdate<UiCommand>,
    ui_event: __sdk::TableUpdate<UiEvent>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(my_api_keys_table::parse_table_update(table_update)?),
                "my_device_metrics" => db_update
                    .my_device_metrics
                    .append(my_device_metrics_table::parse_table_update(table_update)?),
                "my_devices" => db_update
                    .my_devices
                    .append(my_devices_table::parse_table_update(table_update)?),
                "my_files" => db_update
                    .my_files
                    .append(my_files_table::parse_table_update(table_update)?),
                "my_secrets" => db_update
                    .my_secrets
                    .append(my_secrets_table::parse_table_update(table_update)?),
                "my_ssh_endpoints" => db_update
                    .my_ssh_endpoints
                    .append(my_ssh_endpoints_table::parse_table_update(table_update)?),
                "my_ssh_keys" => db_update
                    .my_ssh_keys
                    .append(my_ssh_keys_table::parse_table_update(table_update)?),
                "my_ui_commands" => db_update
                    .my_ui_commands
                    .append(my_ui_commands_table::parse_table_update(table_update)?),
                "my_user" => db_update
                    .my_user
                    .append(my_user_table::parse_table_update(table_update)?),
                "s_3_config_status" => db_update
                    .s_3_config_status
                    .append(s_3_config_status_table::parse_table_update(table_update)?),
                "ui_command" => db_update
                    .ui_command
                    .append(ui_command_table::parse_table_update(table_update)?),
                "ui_event" => db_update
                    .ui_event
                    .append(ui_event_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.ui_command = cache
            .apply_diff_to_table::<UiCommand>("ui_command", &self.ui_command)
            .with_updates_by_pk(|row| &row.id);
        diff.ui_event = self.ui_event.into_event_diff();
        diff.my_api_keys =
            cache.apply_diff_to_table::<ApiKeyMetadata>("my_api_keys", &self.my_api_keys);
        diff.my_device_metrics = cache.apply_diff_to_table::<DeviceMetricSample>(
            "my_device_metrics",
            &self.my_device_metrics,
        );
        diff.my_devices =
            cache.apply_diff_to_table::<DeviceMetadata>("my_devices", &self.my_devices);
        diff.my_files = cache.apply_diff_to_table::<FileMetadata>("my_files", &self.my_files);
        diff.my_secrets =
            cache.apply_diff_to_table::<SecretMetadata>("my_secrets", &self.my_secrets);
        diff.my_ssh_endpoints = cache
            .apply_diff_to_table::<SshEndpointMetadata>("my_ssh_endpoints", &self.my_ssh_endpoints);
        diff.my_ssh_keys =
            cache.apply_diff_to_table::<SshKeyMetadata>("my_ssh_keys", &self.my_ssh_keys);
        diff.my_ui_commands =
            cache.apply_diff_to_table::<UiCommandMetadata>("my_ui_commands", &self.my_ui_commands);
        diff.my_user = cache.apply_diff_to_table::<UserProfile>("my_user", &self.my_user);
        diff.s_3_config_status = cache
            .apply_diff_to_table::<S3ConfigStatus>("s_3_config_status", &self.s_3_config_status);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_device_metrics" => db_update
                    .my_device_metrics
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_devices" => db_update
                    .my_devices
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_files" => db_update
                    .my_files
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_secrets" => db_update
                    .my_secrets
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_ssh_endpoints" => db_update
                    .my_ssh_endpoints
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_ssh_keys" => db_update
                    .my_ssh_keys
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_ui_commands" => db_update
                    .my_ui_commands
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_user" => db_update
                    .my_user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "s_3_config_status" => db_update
                    .s_3_config_status
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ui_command" => db_update
                    .ui_command
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "ui_event" => db_update
                    .ui_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "my_api_keys" => db_update
                    .my_api_keys
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_device_metrics" => db_update
                    .my_device_metrics
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_devices" => db_update
                    .my_devices
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_files" => db_update
                    .my_files
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_secrets" => db_update
                    .my_secrets
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_ssh_endpoints" => db_update
                    .my_ssh_endpoints
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_ssh_keys" => db_update
                    .my_ssh_keys
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_ui_commands" => db_update
                    .my_ui_commands
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_user" => db_update
                    .my_user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "s_3_config_status" => db_update
                    .s_3_config_status
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ui_command" => db_update
                    .ui_command
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "ui_event" => db_update
                    .ui_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    my_api_keys: __sdk::TableAppliedDiff<'r, ApiKeyMetadata>,
    my_device_metrics: __sdk::TableAppliedDiff<'r, DeviceMetricSample>,
    my_devices: __sdk::TableAppliedDiff<'r, DeviceMetadata>,
    my_files: __sdk::TableAppliedDiff<'r, FileMetadata>,
    my_secrets: __sdk::TableAppliedDiff<'r, SecretMetadata>,
    my_ssh_endpoints: __sdk::TableAppliedDiff<'r, SshEndpointMetadata>,
    my_ssh_keys: __sdk::TableAppliedDiff<'r, SshKeyMetadata>,
    my_ui_commands: __sdk::TableAppliedDiff<'r, UiCommandMetadata>,
    my_user: __sdk::TableAppliedDiff<'r, UserProfile>,
    s_3_config_status: __sdk::TableAppliedDiff<'r, S3ConfigStatus>,
    ui_command: __sdk::TableAppliedDiff<'r, UiCommand>,
    ui_event: __sdk::TableAppliedDiff<'r, UiEvent>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<ApiKeyMetadata>(
            "my_api_keys",
            &self.my_api_keys,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DeviceMetricSample>(
            "my_device_metrics",
            &self.my_device_metrics,
            event,
        );
        callbacks.invoke_table_row_callbacks::<DeviceMetadata>(
            "my_devices",
            &self.my_devices,
            event,
        );
        callbacks.invoke_table_row_callbacks::<FileMetadata>("my_files", &self.my_files, event);
        callbacks.invoke_table_row_callbacks::<SecretMetadata>(
            "my_secrets",
            &self.my_secrets,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SshEndpointMetadata>(
            "my_ssh_endpoints",
            &self.my_ssh_endpoints,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SshKeyMetadata>(
            "my_ssh_keys",
            &self.my_ssh_keys,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UiCommandMetadata>(
            "my_ui_commands",
            &self.my_ui_commands,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserProfile>("my_user", &self.my_user, event);
        callbacks.invoke_table_row_callbacks::<S3ConfigStatus>(
            "s_3_config_status",
            &self.s_3_config_status,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UiCommand>("ui_command", &self.ui_command, event);
        callbacks.invoke_table_row_callbacks::<UiEvent>("ui_event", &self.ui_event, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        my_api_keys_table::register_table(client_cache);
        my_device_metrics_table::register_table(client_cache);
        my_devices_table::register_table(client_cache);
        my_files_table::register_table(client_cache);
        my_secrets_table::register_table(client_cache);
        my_ssh_endpoints_table::register_table(client_cache);
        my_ssh_keys_table::register_table(client_cache);
        my_ui_commands_table::register_table(client_cache);
        my_user_table::register_table(client_cache);
        s_3_config_status_table::register_table(client_cache);
        ui_command_table::register_table(client_cache);
        ui_event_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "my_api_keys",
        "my_device_metrics",
        "my_devices",
        "my_files",
        "my_secrets",
        "my_ssh_endpoints",
        "my_ssh_keys",
        "my_ui_commands",
        "my_user",
        "s_3_config_status",
        "ui_command",
        "ui_event",
    ];
}
