// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::api_key_metadata_type::ApiKeyMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_api_keys`.
///
/// Obtain a handle from the [`MyApiKeysTableAccess::my_api_keys`] method on [`super::RemoteTables`],
/// like `ctx.db.my_api_keys()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_api_keys().on_insert(...)`.
pub struct MyApiKeysTableHandle<'ctx> {
    imp: __sdk::TableHandle<ApiKeyMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_api_keys`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyApiKeysTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyApiKeysTableHandle`], which mediates access to the table `my_api_keys`.
    fn my_api_keys(&self) -> MyApiKeysTableHandle<'_>;
}

impl MyApiKeysTableAccess for super::RemoteTables {
    fn my_api_keys(&self) -> MyApiKeysTableHandle<'_> {
        MyApiKeysTableHandle {
            imp: self.imp.get_table::<ApiKeyMetadata>("my_api_keys"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyApiKeysInsertCallbackId(__sdk::CallbackId);
pub struct MyApiKeysDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyApiKeysTableHandle<'ctx> {
    type Row = ApiKeyMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ApiKeyMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyApiKeysInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyApiKeysInsertCallbackId {
        MyApiKeysInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyApiKeysInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyApiKeysDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyApiKeysDeleteCallbackId {
        MyApiKeysDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyApiKeysDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ApiKeyMetadata>("my_api_keys");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ApiKeyMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ApiKeyMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ApiKeyMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_api_keysQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ApiKeyMetadata`.
    fn my_api_keys(&self) -> __sdk::__query_builder::Table<ApiKeyMetadata>;
}

impl my_api_keysQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_api_keys(&self) -> __sdk::__query_builder::Table<ApiKeyMetadata> {
        __sdk::__query_builder::Table::new("my_api_keys")
    }
}
