// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::device_metric_sample_type::DeviceMetricSample;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_device_metrics`.
///
/// Obtain a handle from the [`MyDeviceMetricsTableAccess::my_device_metrics`] method on [`super::RemoteTables`],
/// like `ctx.db.my_device_metrics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_device_metrics().on_insert(...)`.
pub struct MyDeviceMetricsTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeviceMetricSample>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_device_metrics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyDeviceMetricsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyDeviceMetricsTableHandle`], which mediates access to the table `my_device_metrics`.
    fn my_device_metrics(&self) -> MyDeviceMetricsTableHandle<'_>;
}

impl MyDeviceMetricsTableAccess for super::RemoteTables {
    fn my_device_metrics(&self) -> MyDeviceMetricsTableHandle<'_> {
        MyDeviceMetricsTableHandle {
            imp: self
                .imp
                .get_table::<DeviceMetricSample>("my_device_metrics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyDeviceMetricsInsertCallbackId(__sdk::CallbackId);
pub struct MyDeviceMetricsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyDeviceMetricsTableHandle<'ctx> {
    type Row = DeviceMetricSample;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeviceMetricSample> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyDeviceMetricsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceMetricsInsertCallbackId {
        MyDeviceMetricsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyDeviceMetricsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyDeviceMetricsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceMetricsDeleteCallbackId {
        MyDeviceMetricsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyDeviceMetricsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeviceMetricSample>("my_device_metrics");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeviceMetricSample>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeviceMetricSample>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeviceMetricSample`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_device_metricsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeviceMetricSample`.
    fn my_device_metrics(&self) -> __sdk::__query_builder::Table<DeviceMetricSample>;
}

impl my_device_metricsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_device_metrics(&self) -> __sdk::__query_builder::Table<DeviceMetricSample> {
        __sdk::__query_builder::Table::new("my_device_metrics")
    }
}
