// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::device_metadata_type::DeviceMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_devices`.
///
/// Obtain a handle from the [`MyDevicesTableAccess::my_devices`] method on [`super::RemoteTables`],
/// like `ctx.db.my_devices()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_devices().on_insert(...)`.
pub struct MyDevicesTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeviceMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_devices`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyDevicesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyDevicesTableHandle`], which mediates access to the table `my_devices`.
    fn my_devices(&self) -> MyDevicesTableHandle<'_>;
}

impl MyDevicesTableAccess for super::RemoteTables {
    fn my_devices(&self) -> MyDevicesTableHandle<'_> {
        MyDevicesTableHandle {
            imp: self.imp.get_table::<DeviceMetadata>("my_devices"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyDevicesInsertCallbackId(__sdk::CallbackId);
pub struct MyDevicesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyDevicesTableHandle<'ctx> {
    type Row = DeviceMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeviceMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyDevicesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDevicesInsertCallbackId {
        MyDevicesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyDevicesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyDevicesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDevicesDeleteCallbackId {
        MyDevicesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyDevicesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeviceMetadata>("my_devices");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeviceMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeviceMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeviceMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_devicesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeviceMetadata`.
    fn my_devices(&self) -> __sdk::__query_builder::Table<DeviceMetadata>;
}

impl my_devicesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_devices(&self) -> __sdk::__query_builder::Table<DeviceMetadata> {
        __sdk::__query_builder::Table::new("my_devices")
    }
}
