// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::file_metadata_type::FileMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_files`.
///
/// Obtain a handle from the [`MyFilesTableAccess::my_files`] method on [`super::RemoteTables`],
/// like `ctx.db.my_files()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_files().on_insert(...)`.
pub struct MyFilesTableHandle<'ctx> {
    imp: __sdk::TableHandle<FileMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_files`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFilesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFilesTableHandle`], which mediates access to the table `my_files`.
    fn my_files(&self) -> MyFilesTableHandle<'_>;
}

impl MyFilesTableAccess for super::RemoteTables {
    fn my_files(&self) -> MyFilesTableHandle<'_> {
        MyFilesTableHandle {
            imp: self.imp.get_table::<FileMetadata>("my_files"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFilesInsertCallbackId(__sdk::CallbackId);
pub struct MyFilesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyFilesTableHandle<'ctx> {
    type Row = FileMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FileMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFilesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFilesInsertCallbackId {
        MyFilesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFilesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFilesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFilesDeleteCallbackId {
        MyFilesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFilesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FileMetadata>("my_files");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FileMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FileMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FileMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_filesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FileMetadata`.
    fn my_files(&self) -> __sdk::__query_builder::Table<FileMetadata>;
}

impl my_filesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_files(&self) -> __sdk::__query_builder::Table<FileMetadata> {
        __sdk::__query_builder::Table::new("my_files")
    }
}
