// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_key_metadata_type::SshKeyMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ssh_keys`.
///
/// Obtain a handle from the [`MySshKeysTableAccess::my_ssh_keys`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ssh_keys()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ssh_keys().on_insert(...)`.
pub struct MySshKeysTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshKeyMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ssh_keys`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySshKeysTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySshKeysTableHandle`], which mediates access to the table `my_ssh_keys`.
    fn my_ssh_keys(&self) -> MySshKeysTableHandle<'_>;
}

impl MySshKeysTableAccess for super::RemoteTables {
    fn my_ssh_keys(&self) -> MySshKeysTableHandle<'_> {
        MySshKeysTableHandle {
            imp: self.imp.get_table::<SshKeyMetadata>("my_ssh_keys"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySshKeysInsertCallbackId(__sdk::CallbackId);
pub struct MySshKeysDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySshKeysTableHandle<'ctx> {
    type Row = SshKeyMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshKeyMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySshKeysInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshKeysInsertCallbackId {
        MySshKeysInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySshKeysInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySshKeysDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshKeysDeleteCallbackId {
        MySshKeysDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySshKeysDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshKeyMetadata>("my_ssh_keys");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshKeyMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshKeyMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshKeyMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ssh_keysQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshKeyMetadata`.
    fn my_ssh_keys(&self) -> __sdk::__query_builder::Table<SshKeyMetadata>;
}

impl my_ssh_keysQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ssh_keys(&self) -> __sdk::__query_builder::Table<SshKeyMetadata> {
        __sdk::__query_builder::Table::new("my_ssh_keys")
    }
}
