// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_endpoint_metadata_type::SshEndpointMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ssh_endpoints`.
///
/// Obtain a handle from the [`MySshEndpointsTableAccess::my_ssh_endpoints`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ssh_endpoints()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ssh_endpoints().on_insert(...)`.
pub struct MySshEndpointsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshEndpointMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ssh_endpoints`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySshEndpointsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySshEndpointsTableHandle`], which mediates access to the table `my_ssh_endpoints`.
    fn my_ssh_endpoints(&self) -> MySshEndpointsTableHandle<'_>;
}

impl MySshEndpointsTableAccess for super::RemoteTables {
    fn my_ssh_endpoints(&self) -> MySshEndpointsTableHandle<'_> {
        MySshEndpointsTableHandle {
            imp: self
                .imp
                .get_table::<SshEndpointMetadata>("my_ssh_endpoints"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySshEndpointsInsertCallbackId(__sdk::CallbackId);
pub struct MySshEndpointsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySshEndpointsTableHandle<'ctx> {
    type Row = SshEndpointMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshEndpointMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySshEndpointsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshEndpointsInsertCallbackId {
        MySshEndpointsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySshEndpointsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySshEndpointsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshEndpointsDeleteCallbackId {
        MySshEndpointsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySshEndpointsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshEndpointMetadata>("my_ssh_endpoints");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshEndpointMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshEndpointMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshEndpointMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ssh_endpointsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshEndpointMetadata`.
    fn my_ssh_endpoints(&self) -> __sdk::__query_builder::Table<SshEndpointMetadata>;
}

impl my_ssh_endpointsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ssh_endpoints(&self) -> __sdk::__query_builder::Table<SshEndpointMetadata> {
        __sdk::__query_builder::Table::new("my_ssh_endpoints")
    }
}
