// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_relay_session_metadata_type::SshRelaySessionMetadata;
use super::ssh_relay_session_status_type::SshRelaySessionStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ssh_relay_sessions`.
///
/// Obtain a handle from the [`MySshRelaySessionsTableAccess::my_ssh_relay_sessions`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ssh_relay_sessions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ssh_relay_sessions().on_insert(...)`.
pub struct MySshRelaySessionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshRelaySessionMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ssh_relay_sessions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySshRelaySessionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySshRelaySessionsTableHandle`], which mediates access to the table `my_ssh_relay_sessions`.
    fn my_ssh_relay_sessions(&self) -> MySshRelaySessionsTableHandle<'_>;
}

impl MySshRelaySessionsTableAccess for super::RemoteTables {
    fn my_ssh_relay_sessions(&self) -> MySshRelaySessionsTableHandle<'_> {
        MySshRelaySessionsTableHandle {
            imp: self
                .imp
                .get_table::<SshRelaySessionMetadata>("my_ssh_relay_sessions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySshRelaySessionsInsertCallbackId(__sdk::CallbackId);
pub struct MySshRelaySessionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySshRelaySessionsTableHandle<'ctx> {
    type Row = SshRelaySessionMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshRelaySessionMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySshRelaySessionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshRelaySessionsInsertCallbackId {
        MySshRelaySessionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySshRelaySessionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySshRelaySessionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshRelaySessionsDeleteCallbackId {
        MySshRelaySessionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySshRelaySessionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshRelaySessionMetadata>("my_ssh_relay_sessions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshRelaySessionMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshRelaySessionMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshRelaySessionMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ssh_relay_sessionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshRelaySessionMetadata`.
    fn my_ssh_relay_sessions(&self) -> __sdk::__query_builder::Table<SshRelaySessionMetadata>;
}

impl my_ssh_relay_sessionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ssh_relay_sessions(&self) -> __sdk::__query_builder::Table<SshRelaySessionMetadata> {
        __sdk::__query_builder::Table::new("my_ssh_relay_sessions")
    }
}
