// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_relay_device_metadata_type::SshRelayDeviceMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ssh_relay_device`.
///
/// Obtain a handle from the [`MySshRelayDeviceTableAccess::my_ssh_relay_device`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ssh_relay_device()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ssh_relay_device().on_insert(...)`.
pub struct MySshRelayDeviceTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshRelayDeviceMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ssh_relay_device`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySshRelayDeviceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySshRelayDeviceTableHandle`], which mediates access to the table `my_ssh_relay_device`.
    fn my_ssh_relay_device(&self) -> MySshRelayDeviceTableHandle<'_>;
}

impl MySshRelayDeviceTableAccess for super::RemoteTables {
    fn my_ssh_relay_device(&self) -> MySshRelayDeviceTableHandle<'_> {
        MySshRelayDeviceTableHandle {
            imp: self
                .imp
                .get_table::<SshRelayDeviceMetadata>("my_ssh_relay_device"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySshRelayDeviceInsertCallbackId(__sdk::CallbackId);
pub struct MySshRelayDeviceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySshRelayDeviceTableHandle<'ctx> {
    type Row = SshRelayDeviceMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshRelayDeviceMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySshRelayDeviceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshRelayDeviceInsertCallbackId {
        MySshRelayDeviceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySshRelayDeviceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySshRelayDeviceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySshRelayDeviceDeleteCallbackId {
        MySshRelayDeviceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySshRelayDeviceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshRelayDeviceMetadata>("my_ssh_relay_device");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshRelayDeviceMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshRelayDeviceMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshRelayDeviceMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ssh_relay_deviceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshRelayDeviceMetadata`.
    fn my_ssh_relay_device(&self) -> __sdk::__query_builder::Table<SshRelayDeviceMetadata>;
}

impl my_ssh_relay_deviceQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ssh_relay_device(&self) -> __sdk::__query_builder::Table<SshRelayDeviceMetadata> {
        __sdk::__query_builder::Table::new("my_ssh_relay_device")
    }
}
