// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::secret_metadata_type::SecretMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_secrets`.
///
/// Obtain a handle from the [`MySecretsTableAccess::my_secrets`] method on [`super::RemoteTables`],
/// like `ctx.db.my_secrets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_secrets().on_insert(...)`.
pub struct MySecretsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SecretMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_secrets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySecretsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySecretsTableHandle`], which mediates access to the table `my_secrets`.
    fn my_secrets(&self) -> MySecretsTableHandle<'_>;
}

impl MySecretsTableAccess for super::RemoteTables {
    fn my_secrets(&self) -> MySecretsTableHandle<'_> {
        MySecretsTableHandle {
            imp: self.imp.get_table::<SecretMetadata>("my_secrets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySecretsInsertCallbackId(__sdk::CallbackId);
pub struct MySecretsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySecretsTableHandle<'ctx> {
    type Row = SecretMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SecretMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySecretsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySecretsInsertCallbackId {
        MySecretsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySecretsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySecretsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySecretsDeleteCallbackId {
        MySecretsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySecretsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SecretMetadata>("my_secrets");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SecretMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SecretMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SecretMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_secretsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SecretMetadata`.
    fn my_secrets(&self) -> __sdk::__query_builder::Table<SecretMetadata>;
}

impl my_secretsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_secrets(&self) -> __sdk::__query_builder::Table<SecretMetadata> {
        __sdk::__query_builder::Table::new("my_secrets")
    }
}
