// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ui_command_metadata_type::UiCommandMetadata;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_ui_commands`.
///
/// Obtain a handle from the [`MyUiCommandsTableAccess::my_ui_commands`] method on [`super::RemoteTables`],
/// like `ctx.db.my_ui_commands()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_ui_commands().on_insert(...)`.
pub struct MyUiCommandsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UiCommandMetadata>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_ui_commands`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyUiCommandsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyUiCommandsTableHandle`], which mediates access to the table `my_ui_commands`.
    fn my_ui_commands(&self) -> MyUiCommandsTableHandle<'_>;
}

impl MyUiCommandsTableAccess for super::RemoteTables {
    fn my_ui_commands(&self) -> MyUiCommandsTableHandle<'_> {
        MyUiCommandsTableHandle {
            imp: self.imp.get_table::<UiCommandMetadata>("my_ui_commands"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyUiCommandsInsertCallbackId(__sdk::CallbackId);
pub struct MyUiCommandsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyUiCommandsTableHandle<'ctx> {
    type Row = UiCommandMetadata;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UiCommandMetadata> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyUiCommandsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUiCommandsInsertCallbackId {
        MyUiCommandsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyUiCommandsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyUiCommandsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyUiCommandsDeleteCallbackId {
        MyUiCommandsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyUiCommandsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UiCommandMetadata>("my_ui_commands");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UiCommandMetadata>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UiCommandMetadata>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UiCommandMetadata`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_ui_commandsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UiCommandMetadata`.
    fn my_ui_commands(&self) -> __sdk::__query_builder::Table<UiCommandMetadata>;
}

impl my_ui_commandsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_ui_commands(&self) -> __sdk::__query_builder::Table<UiCommandMetadata> {
        __sdk::__query_builder::Table::new("my_ui_commands")
    }
}
