// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OpenSshRelaySessionArgs {
    pub relay_device_id: u64,
    pub endpoint_id: u64,
    pub requester_device_id: Option<u64>,
}

impl From<OpenSshRelaySessionArgs> for super::Reducer {
    fn from(args: OpenSshRelaySessionArgs) -> Self {
        Self::OpenSshRelaySession {
            relay_device_id: args.relay_device_id,
            endpoint_id: args.endpoint_id,
            requester_device_id: args.requester_device_id,
        }
    }
}

impl __sdk::InModule for OpenSshRelaySessionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `open_ssh_relay_session`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait open_ssh_relay_session {
    /// Request that the remote module invoke the reducer `open_ssh_relay_session` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`open_ssh_relay_session:open_ssh_relay_session_then`] to run a callback after the reducer completes.
    fn open_ssh_relay_session(
        &self,
        relay_device_id: u64,
        endpoint_id: u64,
        requester_device_id: Option<u64>,
    ) -> __sdk::Result<()> {
        self.open_ssh_relay_session_then(
            relay_device_id,
            endpoint_id,
            requester_device_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `open_ssh_relay_session` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn open_ssh_relay_session_then(
        &self,
        relay_device_id: u64,
        endpoint_id: u64,
        requester_device_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl open_ssh_relay_session for super::RemoteReducers {
    fn open_ssh_relay_session_then(
        &self,
        relay_device_id: u64,
        endpoint_id: u64,
        requester_device_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            OpenSshRelaySessionArgs {
                relay_device_id,
                endpoint_id,
                requester_device_id,
            },
            callback,
        )
    }
}
