// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PasswordCredential {
    pub user: __sdk::Identity,
    pub password_hash: String,
}

impl __sdk::InModule for PasswordCredential {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PasswordCredential`.
///
/// Provides typed access to columns for query building.
pub struct PasswordCredentialCols {
    pub user: __sdk::__query_builder::Col<PasswordCredential, __sdk::Identity>,
    pub password_hash: __sdk::__query_builder::Col<PasswordCredential, String>,
}

impl __sdk::__query_builder::HasCols for PasswordCredential {
    type Cols = PasswordCredentialCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PasswordCredentialCols {
            user: __sdk::__query_builder::Col::new(table_name, "user"),
            password_hash: __sdk::__query_builder::Col::new(table_name, "password_hash"),
        }
    }
}

/// Indexed column accessor struct for the table `PasswordCredential`.
///
/// Provides typed access to indexed columns for query building.
pub struct PasswordCredentialIxCols {
    pub user: __sdk::__query_builder::IxCol<PasswordCredential, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PasswordCredential {
    type IxCols = PasswordCredentialIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PasswordCredentialIxCols {
            user: __sdk::__query_builder::IxCol::new(table_name, "user"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PasswordCredential {}
