// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PruneDeviceMetricsArgs {
    pub device_id: u64,
    pub older_than: __sdk::Timestamp,
}

impl From<PruneDeviceMetricsArgs> for super::Reducer {
    fn from(args: PruneDeviceMetricsArgs) -> Self {
        Self::PruneDeviceMetrics {
            device_id: args.device_id,
            older_than: args.older_than,
        }
    }
}

impl __sdk::InModule for PruneDeviceMetricsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prune_device_metrics`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prune_device_metrics {
    /// Request that the remote module invoke the reducer `prune_device_metrics` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`prune_device_metrics:prune_device_metrics_then`] to run a callback after the reducer completes.
    fn prune_device_metrics(
        &self,
        device_id: u64,
        older_than: __sdk::Timestamp,
    ) -> __sdk::Result<()> {
        self.prune_device_metrics_then(device_id, older_than, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `prune_device_metrics` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn prune_device_metrics_then(
        &self,
        device_id: u64,
        older_than: __sdk::Timestamp,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl prune_device_metrics for super::RemoteReducers {
    fn prune_device_metrics_then(
        &self,
        device_id: u64,
        older_than: __sdk::Timestamp,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PruneDeviceMetricsArgs {
                device_id,
                older_than,
            },
            callback,
        )
    }
}
