// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterFileArgs {
    pub name: String,
    pub tree_path: Option<String>,
    pub local_path: Option<String>,
    pub hash: String,
    pub size_bytes: u64,
    pub content_type: Option<String>,
}

impl From<RegisterFileArgs> for super::Reducer {
    fn from(args: RegisterFileArgs) -> Self {
        Self::RegisterFile {
            name: args.name,
            tree_path: args.tree_path,
            local_path: args.local_path,
            hash: args.hash,
            size_bytes: args.size_bytes,
            content_type: args.content_type,
        }
    }
}

impl __sdk::InModule for RegisterFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_file {
    /// Request that the remote module invoke the reducer `register_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_file:register_file_then`] to run a callback after the reducer completes.
    fn register_file(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        hash: String,
        size_bytes: u64,
        content_type: Option<String>,
    ) -> __sdk::Result<()> {
        self.register_file_then(
            name,
            tree_path,
            local_path,
            hash,
            size_bytes,
            content_type,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `register_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_file_then(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        hash: String,
        size_bytes: u64,
        content_type: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_file for super::RemoteReducers {
    fn register_file_then(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        hash: String,
        size_bytes: u64,
        content_type: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RegisterFileArgs {
                name,
                tree_path,
                local_path,
                hash,
                size_bytes,
                content_type,
            },
            callback,
        )
    }
}
