// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RenameFileArgs {
    pub file_id: u64,
    pub name: String,
    pub tree_path: Option<String>,
    pub local_path: Option<String>,
}

impl From<RenameFileArgs> for super::Reducer {
    fn from(args: RenameFileArgs) -> Self {
        Self::RenameFile {
            file_id: args.file_id,
            name: args.name,
            tree_path: args.tree_path,
            local_path: args.local_path,
        }
    }
}

impl __sdk::InModule for RenameFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rename_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rename_file {
    /// Request that the remote module invoke the reducer `rename_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rename_file:rename_file_then`] to run a callback after the reducer completes.
    fn rename_file(
        &self,
        file_id: u64,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
    ) -> __sdk::Result<()> {
        self.rename_file_then(file_id, name, tree_path, local_path, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rename_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rename_file_then(
        &self,
        file_id: u64,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl rename_file for super::RemoteReducers {
    fn rename_file_then(
        &self,
        file_id: u64,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RenameFileArgs {
                file_id,
                name,
                tree_path,
                local_path,
            },
            callback,
        )
    }
}
