// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::replace_ticket_type::ReplaceTicket;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ReplaceFileContentArgs {
    pub file_id: u64,
    pub content_type: Option<String>,
}

impl __sdk::InModule for ReplaceFileContentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `replace_file_content`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait replace_file_content {
    fn replace_file_content(&self, file_id: u64, content_type: Option<String>) {
        self.replace_file_content_then(file_id, content_type, |_, _| {});
    }

    fn replace_file_content_then(
        &self,
        file_id: u64,
        content_type: Option<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<ReplaceTicket, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl replace_file_content for super::RemoteProcedures {
    fn replace_file_content_then(
        &self,
        file_id: u64,
        content_type: Option<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<ReplaceTicket, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<ReplaceTicket, String>>(
                "replace_file_content",
                ReplaceFileContentArgs {
                    file_id,
                    content_type,
                },
                __callback,
            );
    }
}
