// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::device_metrics_report_type::DeviceMetricsReport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportDeviceMetricsArgs {
    pub device_id: u64,
    pub report: DeviceMetricsReport,
}

impl From<ReportDeviceMetricsArgs> for super::Reducer {
    fn from(args: ReportDeviceMetricsArgs) -> Self {
        Self::ReportDeviceMetrics {
            device_id: args.device_id,
            report: args.report,
        }
    }
}

impl __sdk::InModule for ReportDeviceMetricsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_device_metrics`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_device_metrics {
    /// Request that the remote module invoke the reducer `report_device_metrics` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_device_metrics:report_device_metrics_then`] to run a callback after the reducer completes.
    fn report_device_metrics(
        &self,
        device_id: u64,
        report: DeviceMetricsReport,
    ) -> __sdk::Result<()> {
        self.report_device_metrics_then(device_id, report, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_device_metrics` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_device_metrics_then(
        &self,
        device_id: u64,
        report: DeviceMetricsReport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_device_metrics for super::RemoteReducers {
    fn report_device_metrics_then(
        &self,
        device_id: u64,
        report: DeviceMetricsReport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReportDeviceMetricsArgs { device_id, report }, callback)
    }
}
