// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::upload_ticket_type::UploadTicket;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct RequestUploadUrlArgs {
    pub name: String,
    pub tree_path: Option<String>,
    pub local_path: Option<String>,
    pub content_type: Option<String>,
}

impl __sdk::InModule for RequestUploadUrlArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `request_upload_url`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait request_upload_url {
    fn request_upload_url(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        content_type: Option<String>,
    ) {
        self.request_upload_url_then(name, tree_path, local_path, content_type, |_, _| {});
    }

    fn request_upload_url_then(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        content_type: Option<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<UploadTicket, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl request_upload_url for super::RemoteProcedures {
    fn request_upload_url_then(
        &self,
        name: String,
        tree_path: Option<String>,
        local_path: Option<String>,
        content_type: Option<String>,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<UploadTicket, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<UploadTicket, String>>(
                "request_upload_url",
                RequestUploadUrlArgs {
                    name,
                    tree_path,
                    local_path,
                    content_type,
                },
                __callback,
            );
    }
}
