// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct RequestDownloadUrlArgs {
    pub file_id: u64,
}

impl __sdk::InModule for RequestDownloadUrlArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `request_download_url`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait request_download_url {
    fn request_download_url(&self, file_id: u64) {
        self.request_download_url_then(file_id, |_, _| {});
    }

    fn request_download_url_then(
        &self,
        file_id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<String, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl request_download_url for super::RemoteProcedures {
    fn request_download_url_then(
        &self,
        file_id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<String, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<String, String>>(
                "request_download_url",
                RequestDownloadUrlArgs { file_id },
                __callback,
            );
    }
}
