// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::secret_value_type::SecretValue;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct RevealSecretArgs {
    pub id: u64,
}

impl __sdk::InModule for RevealSecretArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `reveal_secret`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait reveal_secret {
    fn reveal_secret(&self, id: u64) {
        self.reveal_secret_then(id, |_, _| {});
    }

    fn reveal_secret_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<Option<SecretValue>, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    );
}

impl reveal_secret for super::RemoteProcedures {
    fn reveal_secret_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
            &super::ProcedureEventContext,
            Result<Result<Option<SecretValue>, String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Option<SecretValue>, String>>(
                "reveal_secret",
                RevealSecretArgs { id },
                __callback,
            );
    }
}
