// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ssh_key_value_type::SshKeyValue;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct RevealSshKeyArgs {
    pub id: u64,
}

impl __sdk::InModule for RevealSshKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `reveal_ssh_key`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait reveal_ssh_key {
    fn reveal_ssh_key(&self, id: u64) {
        self.reveal_ssh_key_then(id, |_, _| {});
    }

    fn reveal_ssh_key_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Option<SshKeyValue>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl reveal_ssh_key for super::RemoteProcedures {
    fn reveal_ssh_key_then(
        &self,
        id: u64,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Option<SshKeyValue>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Option<SshKeyValue>, String>>(
                "reveal_ssh_key",
                RevealSshKeyArgs { id },
                __callback,
            );
    }
}
