// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::s_3_config_status_type::S3ConfigStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `s_3_config_status`.
///
/// Obtain a handle from the [`S3ConfigStatusTableAccess::s_3_config_status`] method on [`super::RemoteTables`],
/// like `ctx.db.s_3_config_status()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.s_3_config_status().on_insert(...)`.
pub struct S3ConfigStatusTableHandle<'ctx> {
    imp: __sdk::TableHandle<S3ConfigStatus>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `s_3_config_status`.
///
/// Implemented for [`super::RemoteTables`].
pub trait S3ConfigStatusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`S3ConfigStatusTableHandle`], which mediates access to the table `s_3_config_status`.
    fn s_3_config_status(&self) -> S3ConfigStatusTableHandle<'_>;
}

impl S3ConfigStatusTableAccess for super::RemoteTables {
    fn s_3_config_status(&self) -> S3ConfigStatusTableHandle<'_> {
        S3ConfigStatusTableHandle {
            imp: self.imp.get_table::<S3ConfigStatus>("s_3_config_status"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct S3ConfigStatusInsertCallbackId(__sdk::CallbackId);
pub struct S3ConfigStatusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for S3ConfigStatusTableHandle<'ctx> {
    type Row = S3ConfigStatus;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = S3ConfigStatus> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = S3ConfigStatusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> S3ConfigStatusInsertCallbackId {
        S3ConfigStatusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: S3ConfigStatusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = S3ConfigStatusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> S3ConfigStatusDeleteCallbackId {
        S3ConfigStatusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: S3ConfigStatusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<S3ConfigStatus>("s_3_config_status");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<S3ConfigStatus>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<S3ConfigStatus>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `S3ConfigStatus`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait s_3_config_statusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `S3ConfigStatus`.
    fn s_3_config_status(&self) -> __sdk::__query_builder::Table<S3ConfigStatus>;
}

impl s_3_config_statusQueryTableAccess for __sdk::QueryTableAccessor {
    fn s_3_config_status(&self) -> __sdk::__query_builder::Table<S3ConfigStatus> {
        __sdk::__query_builder::Table::new("s_3_config_status")
    }
}
