// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct S3Config {
    pub id: u32,
    pub bucket: String,
    pub region: String,
    pub endpoint: Option<String>,
    pub access_key_id: String,
    pub secret_access_key: String,
    pub path_prefix: Option<String>,
    pub public_base_url: Option<String>,
}

impl __sdk::InModule for S3Config {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `S3Config`.
///
/// Provides typed access to columns for query building.
pub struct S3ConfigCols {
    pub id: __sdk::__query_builder::Col<S3Config, u32>,
    pub bucket: __sdk::__query_builder::Col<S3Config, String>,
    pub region: __sdk::__query_builder::Col<S3Config, String>,
    pub endpoint: __sdk::__query_builder::Col<S3Config, Option<String>>,
    pub access_key_id: __sdk::__query_builder::Col<S3Config, String>,
    pub secret_access_key: __sdk::__query_builder::Col<S3Config, String>,
    pub path_prefix: __sdk::__query_builder::Col<S3Config, Option<String>>,
    pub public_base_url: __sdk::__query_builder::Col<S3Config, Option<String>>,
}

impl __sdk::__query_builder::HasCols for S3Config {
    type Cols = S3ConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        S3ConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            bucket: __sdk::__query_builder::Col::new(table_name, "bucket"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            endpoint: __sdk::__query_builder::Col::new(table_name, "endpoint"),
            access_key_id: __sdk::__query_builder::Col::new(table_name, "access_key_id"),
            secret_access_key: __sdk::__query_builder::Col::new(table_name, "secret_access_key"),
            path_prefix: __sdk::__query_builder::Col::new(table_name, "path_prefix"),
            public_base_url: __sdk::__query_builder::Col::new(table_name, "public_base_url"),
        }
    }
}

/// Indexed column accessor struct for the table `S3Config`.
///
/// Provides typed access to indexed columns for query building.
pub struct S3ConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<S3Config, u32>,
}

impl __sdk::__query_builder::HasIxCols for S3Config {
    type IxCols = S3ConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        S3ConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for S3Config {}
