// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct S3ConfigStatus {
    pub id: u32,
    pub configured: bool,
    pub bucket: String,
    pub region: String,
    pub endpoint: Option<String>,
    pub path_prefix: Option<String>,
    pub public_base_url: Option<String>,
    pub has_access_key_id: bool,
    pub has_secret_access_key: bool,
}

impl __sdk::InModule for S3ConfigStatus {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `S3ConfigStatus`.
///
/// Provides typed access to columns for query building.
pub struct S3ConfigStatusCols {
    pub id: __sdk::__query_builder::Col<S3ConfigStatus, u32>,
    pub configured: __sdk::__query_builder::Col<S3ConfigStatus, bool>,
    pub bucket: __sdk::__query_builder::Col<S3ConfigStatus, String>,
    pub region: __sdk::__query_builder::Col<S3ConfigStatus, String>,
    pub endpoint: __sdk::__query_builder::Col<S3ConfigStatus, Option<String>>,
    pub path_prefix: __sdk::__query_builder::Col<S3ConfigStatus, Option<String>>,
    pub public_base_url: __sdk::__query_builder::Col<S3ConfigStatus, Option<String>>,
    pub has_access_key_id: __sdk::__query_builder::Col<S3ConfigStatus, bool>,
    pub has_secret_access_key: __sdk::__query_builder::Col<S3ConfigStatus, bool>,
}

impl __sdk::__query_builder::HasCols for S3ConfigStatus {
    type Cols = S3ConfigStatusCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        S3ConfigStatusCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            configured: __sdk::__query_builder::Col::new(table_name, "configured"),
            bucket: __sdk::__query_builder::Col::new(table_name, "bucket"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            endpoint: __sdk::__query_builder::Col::new(table_name, "endpoint"),
            path_prefix: __sdk::__query_builder::Col::new(table_name, "path_prefix"),
            public_base_url: __sdk::__query_builder::Col::new(table_name, "public_base_url"),
            has_access_key_id: __sdk::__query_builder::Col::new(table_name, "has_access_key_id"),
            has_secret_access_key: __sdk::__query_builder::Col::new(
                table_name,
                "has_secret_access_key",
            ),
        }
    }
}
