// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::file_metadata_type::FileMetadata;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct SearchFilesArgs {
    pub query: String,
}

impl __sdk::InModule for SearchFilesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `search_files`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait search_files {
    fn search_files(&self, query: String) {
        self.search_files_then(query, |_, _| {});
    }

    fn search_files_then(
        &self,
        query: String,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Vec<FileMetadata>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl search_files for super::RemoteProcedures {
    fn search_files_then(
        &self,
        query: String,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Vec<FileMetadata>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Vec<FileMetadata>, String>>(
                "search_files",
                SearchFilesArgs { query },
                __callback,
            );
    }
}
