// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SecretMetadata {
    pub id: u64,
    pub env: String,
    pub device_ids: Vec<String>,
    pub permissions: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SecretMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SecretMetadata`.
///
/// Provides typed access to columns for query building.
pub struct SecretMetadataCols {
    pub id: __sdk::__query_builder::Col<SecretMetadata, u64>,
    pub env: __sdk::__query_builder::Col<SecretMetadata, String>,
    pub device_ids: __sdk::__query_builder::Col<SecretMetadata, Vec<String>>,
    pub permissions: __sdk::__query_builder::Col<SecretMetadata, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<SecretMetadata, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SecretMetadata, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SecretMetadata {
    type Cols = SecretMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SecretMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            env: __sdk::__query_builder::Col::new(table_name, "env"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            permissions: __sdk::__query_builder::Col::new(table_name, "permissions"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
