// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendUiEventArgs {
    pub target_device_id: Option<u64>,
    pub kind: String,
    pub payload_json: String,
}

impl From<SendUiEventArgs> for super::Reducer {
    fn from(args: SendUiEventArgs) -> Self {
        Self::SendUiEvent {
            target_device_id: args.target_device_id,
            kind: args.kind,
            payload_json: args.payload_json,
        }
    }
}

impl __sdk::InModule for SendUiEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_ui_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_ui_event {
    /// Request that the remote module invoke the reducer `send_ui_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_ui_event:send_ui_event_then`] to run a callback after the reducer completes.
    fn send_ui_event(
        &self,
        target_device_id: Option<u64>,
        kind: String,
        payload_json: String,
    ) -> __sdk::Result<()> {
        self.send_ui_event_then(target_device_id, kind, payload_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_ui_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_ui_event_then(
        &self,
        target_device_id: Option<u64>,
        kind: String,
        payload_json: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl send_ui_event for super::RemoteReducers {
    fn send_ui_event_then(
        &self,
        target_device_id: Option<u64>,
        kind: String,
        payload_json: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SendUiEventArgs {
                target_device_id,
                kind,
                payload_json,
            },
            callback,
        )
    }
}
