// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSshKeyTagsArgs {
    pub id: u64,
    pub tags: Vec<String>,
}

impl From<SetSshKeyTagsArgs> for super::Reducer {
    fn from(args: SetSshKeyTagsArgs) -> Self {
        Self::SetSshKeyTags {
            id: args.id,
            tags: args.tags,
        }
    }
}

impl __sdk::InModule for SetSshKeyTagsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ssh_key_tags`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ssh_key_tags {
    /// Request that the remote module invoke the reducer `set_ssh_key_tags` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ssh_key_tags:set_ssh_key_tags_then`] to run a callback after the reducer completes.
    fn set_ssh_key_tags(&self, id: u64, tags: Vec<String>) -> __sdk::Result<()> {
        self.set_ssh_key_tags_then(id, tags, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_ssh_key_tags` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ssh_key_tags_then(
        &self,
        id: u64,
        tags: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ssh_key_tags for super::RemoteReducers {
    fn set_ssh_key_tags_then(
        &self,
        id: u64,
        tags: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetSshKeyTagsArgs { id, tags }, callback)
    }
}
