// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSecretPermissionsArgs {
    pub id: u64,
    pub permissions: Vec<String>,
}

impl From<SetSecretPermissionsArgs> for super::Reducer {
    fn from(args: SetSecretPermissionsArgs) -> Self {
        Self::SetSecretPermissions {
            id: args.id,
            permissions: args.permissions,
        }
    }
}

impl __sdk::InModule for SetSecretPermissionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_secret_permissions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_secret_permissions {
    /// Request that the remote module invoke the reducer `set_secret_permissions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_secret_permissions:set_secret_permissions_then`] to run a callback after the reducer completes.
    fn set_secret_permissions(&self, id: u64, permissions: Vec<String>) -> __sdk::Result<()> {
        self.set_secret_permissions_then(id, permissions, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_secret_permissions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_secret_permissions_then(
        &self,
        id: u64,
        permissions: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_secret_permissions for super::RemoteReducers {
    fn set_secret_permissions_then(
        &self,
        id: u64,
        permissions: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetSecretPermissionsArgs { id, permissions }, callback)
    }
}
