// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSshEndpointShellArgs {
    pub id: u64,
    pub shell: Option<String>,
}

impl From<SetSshEndpointShellArgs> for super::Reducer {
    fn from(args: SetSshEndpointShellArgs) -> Self {
        Self::SetSshEndpointShell {
            id: args.id,
            shell: args.shell,
        }
    }
}

impl __sdk::InModule for SetSshEndpointShellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ssh_endpoint_shell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ssh_endpoint_shell {
    /// Request that the remote module invoke the reducer `set_ssh_endpoint_shell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ssh_endpoint_shell:set_ssh_endpoint_shell_then`] to run a callback after the reducer completes.
    fn set_ssh_endpoint_shell(&self, id: u64, shell: Option<String>) -> __sdk::Result<()> {
        self.set_ssh_endpoint_shell_then(id, shell, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_ssh_endpoint_shell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ssh_endpoint_shell_then(
        &self,
        id: u64,
        shell: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ssh_endpoint_shell for super::RemoteReducers {
    fn set_ssh_endpoint_shell_then(
        &self,
        id: u64,
        shell: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetSshEndpointShellArgs { id, shell }, callback)
    }
}
