// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSecretValueArgs {
    pub id: u64,
    pub value: String,
}

impl From<SetSecretValueArgs> for super::Reducer {
    fn from(args: SetSecretValueArgs) -> Self {
        Self::SetSecretValue {
            id: args.id,
            value: args.value,
        }
    }
}

impl __sdk::InModule for SetSecretValueArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_secret_value`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_secret_value {
    /// Request that the remote module invoke the reducer `set_secret_value` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_secret_value:set_secret_value_then`] to run a callback after the reducer completes.
    fn set_secret_value(&self, id: u64, value: String) -> __sdk::Result<()> {
        self.set_secret_value_then(id, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_secret_value` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_secret_value_then(
        &self,
        id: u64,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_secret_value for super::RemoteReducers {
    fn set_secret_value_then(
        &self,
        id: u64,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetSecretValueArgs { id, value }, callback)
    }
}
