// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetDeviceMetricsRetentionArgs {
    pub device_id: u64,
    pub retention_secs: u64,
}

impl From<SetDeviceMetricsRetentionArgs> for super::Reducer {
    fn from(args: SetDeviceMetricsRetentionArgs) -> Self {
        Self::SetDeviceMetricsRetention {
            device_id: args.device_id,
            retention_secs: args.retention_secs,
        }
    }
}

impl __sdk::InModule for SetDeviceMetricsRetentionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_device_metrics_retention`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_device_metrics_retention {
    /// Request that the remote module invoke the reducer `set_device_metrics_retention` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_device_metrics_retention:set_device_metrics_retention_then`] to run a callback after the reducer completes.
    fn set_device_metrics_retention(
        &self,
        device_id: u64,
        retention_secs: u64,
    ) -> __sdk::Result<()> {
        self.set_device_metrics_retention_then(device_id, retention_secs, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_device_metrics_retention` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_device_metrics_retention_then(
        &self,
        device_id: u64,
        retention_secs: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_device_metrics_retention for super::RemoteReducers {
    fn set_device_metrics_retention_then(
        &self,
        device_id: u64,
        retention_secs: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetDeviceMetricsRetentionArgs {
                device_id,
                retention_secs,
            },
            callback,
        )
    }
}
