// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSshEndpointArgs {
    pub name: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub key_id: u64,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub enabled: bool,
    pub login_shell: Option<String>,
}

impl From<SetSshEndpointArgs> for super::Reducer {
    fn from(args: SetSshEndpointArgs) -> Self {
        Self::SetSshEndpoint {
            name: args.name,
            host: args.host,
            port: args.port,
            username: args.username,
            key_id: args.key_id,
            device_ids: args.device_ids,
            tags: args.tags,
            enabled: args.enabled,
            login_shell: args.login_shell,
        }
    }
}

impl __sdk::InModule for SetSshEndpointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ssh_endpoint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ssh_endpoint {
    /// Request that the remote module invoke the reducer `set_ssh_endpoint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ssh_endpoint:set_ssh_endpoint_then`] to run a callback after the reducer completes.
    fn set_ssh_endpoint(
        &self,
        name: String,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
        device_ids: Vec<String>,
        tags: Vec<String>,
        enabled: bool,
        login_shell: Option<String>,
    ) -> __sdk::Result<()> {
        self.set_ssh_endpoint_then(
            name,
            host,
            port,
            username,
            key_id,
            device_ids,
            tags,
            enabled,
            login_shell,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_ssh_endpoint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ssh_endpoint_then(
        &self,
        name: String,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
        device_ids: Vec<String>,
        tags: Vec<String>,
        enabled: bool,
        login_shell: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ssh_endpoint for super::RemoteReducers {
    fn set_ssh_endpoint_then(
        &self,
        name: String,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
        device_ids: Vec<String>,
        tags: Vec<String>,
        enabled: bool,
        login_shell: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetSshEndpointArgs {
                name,
                host,
                port,
                username,
                key_id,
                device_ids,
                tags,
                enabled,
                login_shell,
            },
            callback,
        )
    }
}
