// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSshKeyValueArgs {
    pub id: u64,
    pub public_key: String,
    pub private_key: String,
}

impl From<SetSshKeyValueArgs> for super::Reducer {
    fn from(args: SetSshKeyValueArgs) -> Self {
        Self::SetSshKeyValue {
            id: args.id,
            public_key: args.public_key,
            private_key: args.private_key,
        }
    }
}

impl __sdk::InModule for SetSshKeyValueArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ssh_key_value`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ssh_key_value {
    /// Request that the remote module invoke the reducer `set_ssh_key_value` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ssh_key_value:set_ssh_key_value_then`] to run a callback after the reducer completes.
    fn set_ssh_key_value(
        &self,
        id: u64,
        public_key: String,
        private_key: String,
    ) -> __sdk::Result<()> {
        self.set_ssh_key_value_then(id, public_key, private_key, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_ssh_key_value` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ssh_key_value_then(
        &self,
        id: u64,
        public_key: String,
        private_key: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ssh_key_value for super::RemoteReducers {
    fn set_ssh_key_value_then(
        &self,
        id: u64,
        public_key: String,
        private_key: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetSshKeyValueArgs {
                id,
                public_key,
                private_key,
            },
            callback,
        )
    }
}
