// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSecretArgs {
    pub env: String,
    pub value: String,
    pub device_ids: Vec<String>,
    pub permissions: Vec<String>,
}

impl From<SetSecretArgs> for super::Reducer {
    fn from(args: SetSecretArgs) -> Self {
        Self::SetSecret {
            env: args.env,
            value: args.value,
            device_ids: args.device_ids,
            permissions: args.permissions,
        }
    }
}

impl __sdk::InModule for SetSecretArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_secret`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_secret {
    /// Request that the remote module invoke the reducer `set_secret` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_secret:set_secret_then`] to run a callback after the reducer completes.
    fn set_secret(
        &self,
        env: String,
        value: String,
        device_ids: Vec<String>,
        permissions: Vec<String>,
    ) -> __sdk::Result<()> {
        self.set_secret_then(env, value, device_ids, permissions, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_secret` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_secret_then(
        &self,
        env: String,
        value: String,
        device_ids: Vec<String>,
        permissions: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_secret for super::RemoteReducers {
    fn set_secret_then(
        &self,
        env: String,
        value: String,
        device_ids: Vec<String>,
        permissions: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetSecretArgs {
                env,
                value,
                device_ids,
                permissions,
            },
            callback,
        )
    }
}
