// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSshKeyArgs {
    pub name: String,
    pub public_key: String,
    pub private_key: String,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
}

impl From<SetSshKeyArgs> for super::Reducer {
    fn from(args: SetSshKeyArgs) -> Self {
        Self::SetSshKey {
            name: args.name,
            public_key: args.public_key,
            private_key: args.private_key,
            device_ids: args.device_ids,
            tags: args.tags,
        }
    }
}

impl __sdk::InModule for SetSshKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_ssh_key`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_ssh_key {
    /// Request that the remote module invoke the reducer `set_ssh_key` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_ssh_key:set_ssh_key_then`] to run a callback after the reducer completes.
    fn set_ssh_key(
        &self,
        name: String,
        public_key: String,
        private_key: String,
        device_ids: Vec<String>,
        tags: Vec<String>,
    ) -> __sdk::Result<()> {
        self.set_ssh_key_then(name, public_key, private_key, device_ids, tags, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_ssh_key` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_ssh_key_then(
        &self,
        name: String,
        public_key: String,
        private_key: String,
        device_ids: Vec<String>,
        tags: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_ssh_key for super::RemoteReducers {
    fn set_ssh_key_then(
        &self,
        name: String,
        public_key: String,
        private_key: String,
        device_ids: Vec<String>,
        tags: Vec<String>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetSshKeyArgs {
                name,
                public_key,
                private_key,
                device_ids,
                tags,
            },
            callback,
        )
    }
}
