// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SignUpArgs {
    pub email: String,
    pub password: String,
    pub display_name: Option<String>,
}

impl From<SignUpArgs> for super::Reducer {
    fn from(args: SignUpArgs) -> Self {
        Self::SignUp {
            email: args.email,
            password: args.password,
            display_name: args.display_name,
        }
    }
}

impl __sdk::InModule for SignUpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sign_up`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sign_up {
    /// Request that the remote module invoke the reducer `sign_up` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sign_up:sign_up_then`] to run a callback after the reducer completes.
    fn sign_up(
        &self,
        email: String,
        password: String,
        display_name: Option<String>,
    ) -> __sdk::Result<()> {
        self.sign_up_then(email, password, display_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sign_up` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sign_up_then(
        &self,
        email: String,
        password: String,
        display_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sign_up for super::RemoteReducers {
    fn sign_up_then(
        &self,
        email: String,
        password: String,
        display_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SignUpArgs {
                email,
                password,
                display_name,
            },
            callback,
        )
    }
}
