// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshRelayDevice {
    pub owner: __sdk::Identity,
    pub device_id: u64,
    pub updated_at: __sdk::Timestamp,
    pub listen_url: Option<String>,
}

impl __sdk::InModule for SshRelayDevice {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshRelayDevice`.
///
/// Provides typed access to columns for query building.
pub struct SshRelayDeviceCols {
    pub owner: __sdk::__query_builder::Col<SshRelayDevice, __sdk::Identity>,
    pub device_id: __sdk::__query_builder::Col<SshRelayDevice, u64>,
    pub updated_at: __sdk::__query_builder::Col<SshRelayDevice, __sdk::Timestamp>,
    pub listen_url: __sdk::__query_builder::Col<SshRelayDevice, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SshRelayDevice {
    type Cols = SshRelayDeviceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshRelayDeviceCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            listen_url: __sdk::__query_builder::Col::new(table_name, "listen_url"),
        }
    }
}

/// Indexed column accessor struct for the table `SshRelayDevice`.
///
/// Provides typed access to indexed columns for query building.
pub struct SshRelayDeviceIxCols {
    pub owner: __sdk::__query_builder::IxCol<SshRelayDevice, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for SshRelayDevice {
    type IxCols = SshRelayDeviceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SshRelayDeviceIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SshRelayDevice {}
