// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshEndpoint {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub key_id: u64,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub enabled: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SshEndpoint {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshEndpoint`.
///
/// Provides typed access to columns for query building.
pub struct SshEndpointCols {
    pub id: __sdk::__query_builder::Col<SshEndpoint, u64>,
    pub owner: __sdk::__query_builder::Col<SshEndpoint, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<SshEndpoint, String>,
    pub host: __sdk::__query_builder::Col<SshEndpoint, String>,
    pub port: __sdk::__query_builder::Col<SshEndpoint, u16>,
    pub username: __sdk::__query_builder::Col<SshEndpoint, String>,
    pub key_id: __sdk::__query_builder::Col<SshEndpoint, u64>,
    pub device_ids: __sdk::__query_builder::Col<SshEndpoint, Vec<String>>,
    pub tags: __sdk::__query_builder::Col<SshEndpoint, Vec<String>>,
    pub enabled: __sdk::__query_builder::Col<SshEndpoint, bool>,
    pub created_at: __sdk::__query_builder::Col<SshEndpoint, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SshEndpoint, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SshEndpoint {
    type Cols = SshEndpointCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshEndpointCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            port: __sdk::__query_builder::Col::new(table_name, "port"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            key_id: __sdk::__query_builder::Col::new(table_name, "key_id"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SshEndpoint`.
///
/// Provides typed access to indexed columns for query building.
pub struct SshEndpointIxCols {
    pub id: __sdk::__query_builder::IxCol<SshEndpoint, u64>,
    pub key_id: __sdk::__query_builder::IxCol<SshEndpoint, u64>,
    pub owner: __sdk::__query_builder::IxCol<SshEndpoint, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for SshEndpoint {
    type IxCols = SshEndpointIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SshEndpointIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            key_id: __sdk::__query_builder::IxCol::new(table_name, "key_id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SshEndpoint {}
