// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshRelayDeviceMetadata {
    pub owner: __sdk::Identity,
    pub device_id: u64,
    pub updated_at: __sdk::Timestamp,
    pub listen_url: Option<String>,
}

impl __sdk::InModule for SshRelayDeviceMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshRelayDeviceMetadata`.
///
/// Provides typed access to columns for query building.
pub struct SshRelayDeviceMetadataCols {
    pub owner: __sdk::__query_builder::Col<SshRelayDeviceMetadata, __sdk::Identity>,
    pub device_id: __sdk::__query_builder::Col<SshRelayDeviceMetadata, u64>,
    pub updated_at: __sdk::__query_builder::Col<SshRelayDeviceMetadata, __sdk::Timestamp>,
    pub listen_url: __sdk::__query_builder::Col<SshRelayDeviceMetadata, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SshRelayDeviceMetadata {
    type Cols = SshRelayDeviceMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshRelayDeviceMetadataCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            device_id: __sdk::__query_builder::Col::new(table_name, "device_id"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            listen_url: __sdk::__query_builder::Col::new(table_name, "listen_url"),
        }
    }
}
