// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshKeyMetadata {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub public_key: String,
    pub fingerprint: String,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SshKeyMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshKeyMetadata`.
///
/// Provides typed access to columns for query building.
pub struct SshKeyMetadataCols {
    pub id: __sdk::__query_builder::Col<SshKeyMetadata, u64>,
    pub owner: __sdk::__query_builder::Col<SshKeyMetadata, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<SshKeyMetadata, String>,
    pub public_key: __sdk::__query_builder::Col<SshKeyMetadata, String>,
    pub fingerprint: __sdk::__query_builder::Col<SshKeyMetadata, String>,
    pub device_ids: __sdk::__query_builder::Col<SshKeyMetadata, Vec<String>>,
    pub tags: __sdk::__query_builder::Col<SshKeyMetadata, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<SshKeyMetadata, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SshKeyMetadata, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SshKeyMetadata {
    type Cols = SshKeyMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshKeyMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            public_key: __sdk::__query_builder::Col::new(table_name, "public_key"),
            fingerprint: __sdk::__query_builder::Col::new(table_name, "fingerprint"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
