// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshKeyValue {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub public_key: String,
    pub private_key: String,
    pub fingerprint: String,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SshKeyValue {
    type Module = super::RemoteModule;
}
