// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_relay_session_status_type::SshRelaySessionStatus;
use super::ssh_relay_session_type::SshRelaySession;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ssh_relay_session`.
///
/// Obtain a handle from the [`SshRelaySessionTableAccess::ssh_relay_session`] method on [`super::RemoteTables`],
/// like `ctx.db.ssh_relay_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ssh_relay_session().on_insert(...)`.
pub struct SshRelaySessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshRelaySession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ssh_relay_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SshRelaySessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SshRelaySessionTableHandle`], which mediates access to the table `ssh_relay_session`.
    fn ssh_relay_session(&self) -> SshRelaySessionTableHandle<'_>;
}

impl SshRelaySessionTableAccess for super::RemoteTables {
    fn ssh_relay_session(&self) -> SshRelaySessionTableHandle<'_> {
        SshRelaySessionTableHandle {
            imp: self.imp.get_table::<SshRelaySession>("ssh_relay_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SshRelaySessionInsertCallbackId(__sdk::CallbackId);
pub struct SshRelaySessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SshRelaySessionTableHandle<'ctx> {
    type Row = SshRelaySession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshRelaySession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SshRelaySessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SshRelaySessionInsertCallbackId {
        SshRelaySessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SshRelaySessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SshRelaySessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SshRelaySessionDeleteCallbackId {
        SshRelaySessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SshRelaySessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SshRelaySessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SshRelaySessionTableHandle<'ctx> {
    type UpdateCallbackId = SshRelaySessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SshRelaySessionUpdateCallbackId {
        SshRelaySessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SshRelaySessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ssh_relay_session`,
/// which allows point queries on the field of the same name
/// via the [`SshRelaySessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ssh_relay_session().id().find(...)`.
pub struct SshRelaySessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SshRelaySession, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SshRelaySessionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ssh_relay_session`.
    pub fn id(&self) -> SshRelaySessionIdUnique<'ctx> {
        SshRelaySessionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SshRelaySessionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SshRelaySession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshRelaySession>("ssh_relay_session");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshRelaySession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshRelaySession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshRelaySession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ssh_relay_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshRelaySession`.
    fn ssh_relay_session(&self) -> __sdk::__query_builder::Table<SshRelaySession>;
}

impl ssh_relay_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn ssh_relay_session(&self) -> __sdk::__query_builder::Table<SshRelaySession> {
        __sdk::__query_builder::Table::new("ssh_relay_session")
    }
}
