// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshKey {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub public_key: String,
    pub private_key: String,
    pub fingerprint: String,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SshKey {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshKey`.
///
/// Provides typed access to columns for query building.
pub struct SshKeyCols {
    pub id: __sdk::__query_builder::Col<SshKey, u64>,
    pub owner: __sdk::__query_builder::Col<SshKey, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<SshKey, String>,
    pub public_key: __sdk::__query_builder::Col<SshKey, String>,
    pub private_key: __sdk::__query_builder::Col<SshKey, String>,
    pub fingerprint: __sdk::__query_builder::Col<SshKey, String>,
    pub device_ids: __sdk::__query_builder::Col<SshKey, Vec<String>>,
    pub tags: __sdk::__query_builder::Col<SshKey, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<SshKey, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SshKey, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SshKey {
    type Cols = SshKeyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshKeyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            public_key: __sdk::__query_builder::Col::new(table_name, "public_key"),
            private_key: __sdk::__query_builder::Col::new(table_name, "private_key"),
            fingerprint: __sdk::__query_builder::Col::new(table_name, "fingerprint"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SshKey`.
///
/// Provides typed access to indexed columns for query building.
pub struct SshKeyIxCols {
    pub id: __sdk::__query_builder::IxCol<SshKey, u64>,
    pub owner: __sdk::__query_builder::IxCol<SshKey, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for SshKey {
    type IxCols = SshKeyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SshKeyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SshKey {}
