// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ssh_relay_session_status_type::SshRelaySessionStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshRelaySession {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub requester_device_id: Option<u64>,
    pub relay_device_id: u64,
    pub endpoint_id: u64,
    pub status: SshRelaySessionStatus,
    pub created_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
    pub auth_token: Option<String>,
}

impl __sdk::InModule for SshRelaySession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshRelaySession`.
///
/// Provides typed access to columns for query building.
pub struct SshRelaySessionCols {
    pub id: __sdk::__query_builder::Col<SshRelaySession, u64>,
    pub owner: __sdk::__query_builder::Col<SshRelaySession, __sdk::Identity>,
    pub requester_device_id: __sdk::__query_builder::Col<SshRelaySession, Option<u64>>,
    pub relay_device_id: __sdk::__query_builder::Col<SshRelaySession, u64>,
    pub endpoint_id: __sdk::__query_builder::Col<SshRelaySession, u64>,
    pub status: __sdk::__query_builder::Col<SshRelaySession, SshRelaySessionStatus>,
    pub created_at: __sdk::__query_builder::Col<SshRelaySession, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<SshRelaySession, __sdk::Timestamp>,
    pub auth_token: __sdk::__query_builder::Col<SshRelaySession, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SshRelaySession {
    type Cols = SshRelaySessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshRelaySessionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            requester_device_id: __sdk::__query_builder::Col::new(
                table_name,
                "requester_device_id",
            ),
            relay_device_id: __sdk::__query_builder::Col::new(table_name, "relay_device_id"),
            endpoint_id: __sdk::__query_builder::Col::new(table_name, "endpoint_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            auth_token: __sdk::__query_builder::Col::new(table_name, "auth_token"),
        }
    }
}

/// Indexed column accessor struct for the table `SshRelaySession`.
///
/// Provides typed access to indexed columns for query building.
pub struct SshRelaySessionIxCols {
    pub endpoint_id: __sdk::__query_builder::IxCol<SshRelaySession, u64>,
    pub id: __sdk::__query_builder::IxCol<SshRelaySession, u64>,
    pub owner: __sdk::__query_builder::IxCol<SshRelaySession, __sdk::Identity>,
    pub relay_device_id: __sdk::__query_builder::IxCol<SshRelaySession, u64>,
}

impl __sdk::__query_builder::HasIxCols for SshRelaySession {
    type IxCols = SshRelaySessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SshRelaySessionIxCols {
            endpoint_id: __sdk::__query_builder::IxCol::new(table_name, "endpoint_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            relay_device_id: __sdk::__query_builder::IxCol::new(table_name, "relay_device_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SshRelaySession {}
