// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SshEndpointMetadata {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub key_id: u64,
    pub device_ids: Vec<String>,
    pub tags: Vec<String>,
    pub enabled: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SshEndpointMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SshEndpointMetadata`.
///
/// Provides typed access to columns for query building.
pub struct SshEndpointMetadataCols {
    pub id: __sdk::__query_builder::Col<SshEndpointMetadata, u64>,
    pub owner: __sdk::__query_builder::Col<SshEndpointMetadata, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<SshEndpointMetadata, String>,
    pub host: __sdk::__query_builder::Col<SshEndpointMetadata, String>,
    pub port: __sdk::__query_builder::Col<SshEndpointMetadata, u16>,
    pub username: __sdk::__query_builder::Col<SshEndpointMetadata, String>,
    pub key_id: __sdk::__query_builder::Col<SshEndpointMetadata, u64>,
    pub device_ids: __sdk::__query_builder::Col<SshEndpointMetadata, Vec<String>>,
    pub tags: __sdk::__query_builder::Col<SshEndpointMetadata, Vec<String>>,
    pub enabled: __sdk::__query_builder::Col<SshEndpointMetadata, bool>,
    pub created_at: __sdk::__query_builder::Col<SshEndpointMetadata, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SshEndpointMetadata, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SshEndpointMetadata {
    type Cols = SshEndpointMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SshEndpointMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            port: __sdk::__query_builder::Col::new(table_name, "port"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            key_id: __sdk::__query_builder::Col::new(table_name, "key_id"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}
