// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ssh_relay_device_type::SshRelayDevice;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ssh_relay_device`.
///
/// Obtain a handle from the [`SshRelayDeviceTableAccess::ssh_relay_device`] method on [`super::RemoteTables`],
/// like `ctx.db.ssh_relay_device()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ssh_relay_device().on_insert(...)`.
pub struct SshRelayDeviceTableHandle<'ctx> {
    imp: __sdk::TableHandle<SshRelayDevice>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ssh_relay_device`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SshRelayDeviceTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SshRelayDeviceTableHandle`], which mediates access to the table `ssh_relay_device`.
    fn ssh_relay_device(&self) -> SshRelayDeviceTableHandle<'_>;
}

impl SshRelayDeviceTableAccess for super::RemoteTables {
    fn ssh_relay_device(&self) -> SshRelayDeviceTableHandle<'_> {
        SshRelayDeviceTableHandle {
            imp: self.imp.get_table::<SshRelayDevice>("ssh_relay_device"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SshRelayDeviceInsertCallbackId(__sdk::CallbackId);
pub struct SshRelayDeviceDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SshRelayDeviceTableHandle<'ctx> {
    type Row = SshRelayDevice;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SshRelayDevice> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SshRelayDeviceInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SshRelayDeviceInsertCallbackId {
        SshRelayDeviceInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SshRelayDeviceInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SshRelayDeviceDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SshRelayDeviceDeleteCallbackId {
        SshRelayDeviceDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SshRelayDeviceDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SshRelayDeviceUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SshRelayDeviceTableHandle<'ctx> {
    type UpdateCallbackId = SshRelayDeviceUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SshRelayDeviceUpdateCallbackId {
        SshRelayDeviceUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SshRelayDeviceUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `owner` unique index on the table `ssh_relay_device`,
/// which allows point queries on the field of the same name
/// via the [`SshRelayDeviceOwnerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ssh_relay_device().owner().find(...)`.
pub struct SshRelayDeviceOwnerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SshRelayDevice, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SshRelayDeviceTableHandle<'ctx> {
    /// Get a handle on the `owner` unique index on the table `ssh_relay_device`.
    pub fn owner(&self) -> SshRelayDeviceOwnerUnique<'ctx> {
        SshRelayDeviceOwnerUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("owner"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SshRelayDeviceOwnerUnique<'ctx> {
    /// Find the subscribed row whose `owner` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<SshRelayDevice> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SshRelayDevice>("ssh_relay_device");
    _table.add_unique_constraint::<__sdk::Identity>("owner", |row| &row.owner);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SshRelayDevice>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SshRelayDevice>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SshRelayDevice`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ssh_relay_deviceQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SshRelayDevice`.
    fn ssh_relay_device(&self) -> __sdk::__query_builder::Table<SshRelayDevice>;
}

impl ssh_relay_deviceQueryTableAccess for __sdk::QueryTableAccessor {
    fn ssh_relay_device(&self) -> __sdk::__query_builder::Table<SshRelayDevice> {
        __sdk::__query_builder::Table::new("ssh_relay_device")
    }
}
