// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UiCommand {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub target_device_id: Option<u64>,
    pub kind: String,
    pub payload_json: String,
    pub created_at: __sdk::Timestamp,
    pub handled_at: Option<__sdk::Timestamp>,
    pub handled_by_device_id: Option<u64>,
}

impl __sdk::InModule for UiCommand {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UiCommand`.
///
/// Provides typed access to columns for query building.
pub struct UiCommandCols {
    pub id: __sdk::__query_builder::Col<UiCommand, u64>,
    pub owner: __sdk::__query_builder::Col<UiCommand, __sdk::Identity>,
    pub target_device_id: __sdk::__query_builder::Col<UiCommand, Option<u64>>,
    pub kind: __sdk::__query_builder::Col<UiCommand, String>,
    pub payload_json: __sdk::__query_builder::Col<UiCommand, String>,
    pub created_at: __sdk::__query_builder::Col<UiCommand, __sdk::Timestamp>,
    pub handled_at: __sdk::__query_builder::Col<UiCommand, Option<__sdk::Timestamp>>,
    pub handled_by_device_id: __sdk::__query_builder::Col<UiCommand, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for UiCommand {
    type Cols = UiCommandCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UiCommandCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            target_device_id: __sdk::__query_builder::Col::new(table_name, "target_device_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            payload_json: __sdk::__query_builder::Col::new(table_name, "payload_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            handled_at: __sdk::__query_builder::Col::new(table_name, "handled_at"),
            handled_by_device_id: __sdk::__query_builder::Col::new(
                table_name,
                "handled_by_device_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `UiCommand`.
///
/// Provides typed access to indexed columns for query building.
pub struct UiCommandIxCols {
    pub id: __sdk::__query_builder::IxCol<UiCommand, u64>,
    pub owner: __sdk::__query_builder::IxCol<UiCommand, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UiCommand {
    type IxCols = UiCommandIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UiCommandIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UiCommand {}
