// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ui_command_type::UiCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ui_command`.
///
/// Obtain a handle from the [`UiCommandTableAccess::ui_command`] method on [`super::RemoteTables`],
/// like `ctx.db.ui_command()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ui_command().on_insert(...)`.
pub struct UiCommandTableHandle<'ctx> {
    imp: __sdk::TableHandle<UiCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ui_command`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UiCommandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UiCommandTableHandle`], which mediates access to the table `ui_command`.
    fn ui_command(&self) -> UiCommandTableHandle<'_>;
}

impl UiCommandTableAccess for super::RemoteTables {
    fn ui_command(&self) -> UiCommandTableHandle<'_> {
        UiCommandTableHandle {
            imp: self.imp.get_table::<UiCommand>("ui_command"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UiCommandInsertCallbackId(__sdk::CallbackId);
pub struct UiCommandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UiCommandTableHandle<'ctx> {
    type Row = UiCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UiCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UiCommandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UiCommandInsertCallbackId {
        UiCommandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UiCommandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UiCommandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UiCommandDeleteCallbackId {
        UiCommandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UiCommandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UiCommandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UiCommandTableHandle<'ctx> {
    type UpdateCallbackId = UiCommandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UiCommandUpdateCallbackId {
        UiCommandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UiCommandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ui_command`,
/// which allows point queries on the field of the same name
/// via the [`UiCommandIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ui_command().id().find(...)`.
pub struct UiCommandIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UiCommand, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UiCommandTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ui_command`.
    pub fn id(&self) -> UiCommandIdUnique<'ctx> {
        UiCommandIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UiCommandIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UiCommand> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UiCommand>("ui_command");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UiCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UiCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UiCommand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ui_commandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UiCommand`.
    fn ui_command(&self) -> __sdk::__query_builder::Table<UiCommand>;
}

impl ui_commandQueryTableAccess for __sdk::QueryTableAccessor {
    fn ui_command(&self) -> __sdk::__query_builder::Table<UiCommand> {
        __sdk::__query_builder::Table::new("ui_command")
    }
}
