// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UiCommandMetadata {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub target_device_id: Option<u64>,
    pub kind: String,
    pub payload_json: String,
    pub created_at: __sdk::Timestamp,
    pub handled_at: Option<__sdk::Timestamp>,
    pub handled_by_device_id: Option<u64>,
}

impl __sdk::InModule for UiCommandMetadata {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UiCommandMetadata`.
///
/// Provides typed access to columns for query building.
pub struct UiCommandMetadataCols {
    pub id: __sdk::__query_builder::Col<UiCommandMetadata, u64>,
    pub owner: __sdk::__query_builder::Col<UiCommandMetadata, __sdk::Identity>,
    pub target_device_id: __sdk::__query_builder::Col<UiCommandMetadata, Option<u64>>,
    pub kind: __sdk::__query_builder::Col<UiCommandMetadata, String>,
    pub payload_json: __sdk::__query_builder::Col<UiCommandMetadata, String>,
    pub created_at: __sdk::__query_builder::Col<UiCommandMetadata, __sdk::Timestamp>,
    pub handled_at: __sdk::__query_builder::Col<UiCommandMetadata, Option<__sdk::Timestamp>>,
    pub handled_by_device_id: __sdk::__query_builder::Col<UiCommandMetadata, Option<u64>>,
}

impl __sdk::__query_builder::HasCols for UiCommandMetadata {
    type Cols = UiCommandMetadataCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UiCommandMetadataCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            target_device_id: __sdk::__query_builder::Col::new(table_name, "target_device_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            payload_json: __sdk::__query_builder::Col::new(table_name, "payload_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            handled_at: __sdk::__query_builder::Col::new(table_name, "handled_at"),
            handled_by_device_id: __sdk::__query_builder::Col::new(
                table_name,
                "handled_by_device_id",
            ),
        }
    }
}
