// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UiEvent {
    pub owner: __sdk::Identity,
    pub target_device_id: Option<u64>,
    pub command_id: Option<u64>,
    pub kind: String,
    pub payload_json: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for UiEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UiEvent`.
///
/// Provides typed access to columns for query building.
pub struct UiEventCols {
    pub owner: __sdk::__query_builder::Col<UiEvent, __sdk::Identity>,
    pub target_device_id: __sdk::__query_builder::Col<UiEvent, Option<u64>>,
    pub command_id: __sdk::__query_builder::Col<UiEvent, Option<u64>>,
    pub kind: __sdk::__query_builder::Col<UiEvent, String>,
    pub payload_json: __sdk::__query_builder::Col<UiEvent, String>,
    pub created_at: __sdk::__query_builder::Col<UiEvent, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for UiEvent {
    type Cols = UiEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UiEventCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            target_device_id: __sdk::__query_builder::Col::new(table_name, "target_device_id"),
            command_id: __sdk::__query_builder::Col::new(table_name, "command_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            payload_json: __sdk::__query_builder::Col::new(table_name, "payload_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `UiEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct UiEventIxCols {}

impl __sdk::__query_builder::HasIxCols for UiEvent {
    type IxCols = UiEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UiEventIxCols {}
    }
}
