// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ui_event_type::UiEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ui_event`.
///
/// Obtain a handle from the [`UiEventTableAccess::ui_event`] method on [`super::RemoteTables`],
/// like `ctx.db.ui_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ui_event().on_insert(...)`.
pub struct UiEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<UiEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ui_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UiEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UiEventTableHandle`], which mediates access to the table `ui_event`.
    fn ui_event(&self) -> UiEventTableHandle<'_>;
}

impl UiEventTableAccess for super::RemoteTables {
    fn ui_event(&self) -> UiEventTableHandle<'_> {
        UiEventTableHandle {
            imp: self.imp.get_table::<UiEvent>("ui_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UiEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::EventTable for UiEventTableHandle<'ctx> {
    type Row = UiEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UiEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UiEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UiEventInsertCallbackId {
        UiEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UiEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UiEvent>("ui_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UiEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UiEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UiEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ui_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UiEvent`.
    fn ui_event(&self) -> __sdk::__query_builder::Table<UiEvent>;
}

impl ui_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn ui_event(&self) -> __sdk::__query_builder::Table<UiEvent> {
        __sdk::__query_builder::Table::new("ui_event")
    }
}
