// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateEmailArgs {
    pub new_email: String,
    pub current_password: String,
}

impl From<UpdateEmailArgs> for super::Reducer {
    fn from(args: UpdateEmailArgs) -> Self {
        Self::UpdateEmail {
            new_email: args.new_email,
            current_password: args.current_password,
        }
    }
}

impl __sdk::InModule for UpdateEmailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_email`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_email {
    /// Request that the remote module invoke the reducer `update_email` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_email:update_email_then`] to run a callback after the reducer completes.
    fn update_email(&self, new_email: String, current_password: String) -> __sdk::Result<()> {
        self.update_email_then(new_email, current_password, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_email` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_email_then(
        &self,
        new_email: String,
        current_password: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_email for super::RemoteReducers {
    fn update_email_then(
        &self,
        new_email: String,
        current_password: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateEmailArgs {
                new_email,
                current_password,
            },
            callback,
        )
    }
}
