// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePasswordArgs {
    pub current_password: String,
    pub new_password: String,
}

impl From<UpdatePasswordArgs> for super::Reducer {
    fn from(args: UpdatePasswordArgs) -> Self {
        Self::UpdatePassword {
            current_password: args.current_password,
            new_password: args.new_password,
        }
    }
}

impl __sdk::InModule for UpdatePasswordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_password`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_password {
    /// Request that the remote module invoke the reducer `update_password` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_password:update_password_then`] to run a callback after the reducer completes.
    fn update_password(&self, current_password: String, new_password: String) -> __sdk::Result<()> {
        self.update_password_then(current_password, new_password, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_password` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_password_then(
        &self,
        current_password: String,
        new_password: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_password for super::RemoteReducers {
    fn update_password_then(
        &self,
        current_password: String,
        new_password: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePasswordArgs {
                current_password,
                new_password,
            },
            callback,
        )
    }
}
