// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateS3ConfigArgs {
    pub bucket: String,
    pub region: String,
    pub endpoint: Option<String>,
    pub access_key_id: Option<String>,
    pub secret_access_key: Option<String>,
    pub path_prefix: Option<String>,
    pub public_base_url: Option<String>,
}

impl From<UpdateS3ConfigArgs> for super::Reducer {
    fn from(args: UpdateS3ConfigArgs) -> Self {
        Self::UpdateS3Config {
            bucket: args.bucket,
            region: args.region,
            endpoint: args.endpoint,
            access_key_id: args.access_key_id,
            secret_access_key: args.secret_access_key,
            path_prefix: args.path_prefix,
            public_base_url: args.public_base_url,
        }
    }
}

impl __sdk::InModule for UpdateS3ConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_s_3_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_s_3_config {
    /// Request that the remote module invoke the reducer `update_s_3_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_s_3_config:update_s_3_config_then`] to run a callback after the reducer completes.
    fn update_s_3_config(
        &self,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,
    ) -> __sdk::Result<()> {
        self.update_s_3_config_then(
            bucket,
            region,
            endpoint,
            access_key_id,
            secret_access_key,
            path_prefix,
            public_base_url,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_s_3_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_s_3_config_then(
        &self,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_s_3_config for super::RemoteReducers {
    fn update_s_3_config_then(
        &self,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateS3ConfigArgs {
                bucket,
                region,
                endpoint,
                access_key_id,
                secret_access_key,
                path_prefix,
                public_base_url,
            },
            callback,
        )
    }
}
