// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct UpdateS3ConfigWithCredentialsArgs {
    pub email: String,
    pub password: String,
    pub bucket: String,
    pub region: String,
    pub endpoint: Option<String>,
    pub access_key_id: Option<String>,
    pub secret_access_key: Option<String>,
    pub path_prefix: Option<String>,
    pub public_base_url: Option<String>,
}

impl __sdk::InModule for UpdateS3ConfigWithCredentialsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `update_s_3_config_with_credentials`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait update_s_3_config_with_credentials {
    fn update_s_3_config_with_credentials(
        &self,
        email: String,
        password: String,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,
    ) {
        self.update_s_3_config_with_credentials_then(
            email,
            password,
            bucket,
            region,
            endpoint,
            access_key_id,
            secret_access_key,
            path_prefix,
            public_base_url,
            |_, _| {},
        );
    }

    fn update_s_3_config_with_credentials_then(
        &self,
        email: String,
        password: String,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl update_s_3_config_with_credentials for super::RemoteProcedures {
    fn update_s_3_config_with_credentials_then(
        &self,
        email: String,
        password: String,
        bucket: String,
        region: String,
        endpoint: Option<String>,
        access_key_id: Option<String>,
        secret_access_key: Option<String>,
        path_prefix: Option<String>,
        public_base_url: Option<String>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<(), String>>(
                "update_s_3_config_with_credentials",
                UpdateS3ConfigWithCredentialsArgs {
                    email,
                    password,
                    bucket,
                    region,
                    endpoint,
                    access_key_id,
                    secret_access_key,
                    path_prefix,
                    public_base_url,
                },
                __callback,
            );
    }
}
