// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateApiKeyPermissionsArgs {
    pub api_key_id: u64,
    pub permissions: Vec<String>,
}

impl From<UpdateApiKeyPermissionsArgs> for super::Reducer {
    fn from(args: UpdateApiKeyPermissionsArgs) -> Self {
        Self::UpdateApiKeyPermissions {
            api_key_id: args.api_key_id,
            permissions: args.permissions,
        }
    }
}

impl __sdk::InModule for UpdateApiKeyPermissionsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_api_key_permissions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_api_key_permissions {
    /// Request that the remote module invoke the reducer `update_api_key_permissions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_api_key_permissions:update_api_key_permissions_then`] to run a callback after the reducer completes.
    fn update_api_key_permissions(
        &self,
        api_key_id: u64,
        permissions: Vec<String>,
    ) -> __sdk::Result<()> {
        self.update_api_key_permissions_then(api_key_id, permissions, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_api_key_permissions` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_api_key_permissions_then(
        &self,
        api_key_id: u64,
        permissions: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_api_key_permissions for super::RemoteReducers {
    fn update_api_key_permissions_then(
        &self,
        api_key_id: u64,
        permissions: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateApiKeyPermissionsArgs {
                api_key_id,
                permissions,
            },
            callback,
        )
    }
}
