// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSshEndpointArgs {
    pub id: u64,
    pub host: String,
    pub port: u16,
    pub username: String,
    pub key_id: u64,
}

impl From<UpdateSshEndpointArgs> for super::Reducer {
    fn from(args: UpdateSshEndpointArgs) -> Self {
        Self::UpdateSshEndpoint {
            id: args.id,
            host: args.host,
            port: args.port,
            username: args.username,
            key_id: args.key_id,
        }
    }
}

impl __sdk::InModule for UpdateSshEndpointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_ssh_endpoint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_ssh_endpoint {
    /// Request that the remote module invoke the reducer `update_ssh_endpoint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_ssh_endpoint:update_ssh_endpoint_then`] to run a callback after the reducer completes.
    fn update_ssh_endpoint(
        &self,
        id: u64,
        host: String,
        port: u16,
        username: String,
        key_id: u64,
    ) -> __sdk::Result<()> {
        self.update_ssh_endpoint_then(id, host, port, username, key_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_ssh_endpoint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_ssh_endpoint_then(
        &self,
        id: u64,
        host: String,
        port: u16,
        username: String,
        key_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_ssh_endpoint for super::RemoteReducers {
    fn update_ssh_endpoint_then(
        &self,
        id: u64,
        host: String,
        port: u16,
        username: String,
        key_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateSshEndpointArgs {
                id,
                host,
                port,
                username,
                key_id,
            },
            callback,
        )
    }
}
