// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfile {
    pub identity: __sdk::Identity,
    pub email: String,
    pub display_name: Option<String>,
    pub role: String,
    pub created_at: __sdk::Timestamp,
    pub last_login_at: __sdk::Timestamp,
}

impl __sdk::InModule for UserProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserProfile`.
///
/// Provides typed access to columns for query building.
pub struct UserProfileCols {
    pub identity: __sdk::__query_builder::Col<UserProfile, __sdk::Identity>,
    pub email: __sdk::__query_builder::Col<UserProfile, String>,
    pub display_name: __sdk::__query_builder::Col<UserProfile, Option<String>>,
    pub role: __sdk::__query_builder::Col<UserProfile, String>,
    pub created_at: __sdk::__query_builder::Col<UserProfile, __sdk::Timestamp>,
    pub last_login_at: __sdk::__query_builder::Col<UserProfile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for UserProfile {
    type Cols = UserProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_login_at: __sdk::__query_builder::Col::new(table_name, "last_login_at"),
        }
    }
}
