// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserSecret {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub env: String,
    pub value: String,
    pub device_ids: Vec<String>,
    pub permissions: Vec<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for UserSecret {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserSecret`.
///
/// Provides typed access to columns for query building.
pub struct UserSecretCols {
    pub id: __sdk::__query_builder::Col<UserSecret, u64>,
    pub owner: __sdk::__query_builder::Col<UserSecret, __sdk::Identity>,
    pub env: __sdk::__query_builder::Col<UserSecret, String>,
    pub value: __sdk::__query_builder::Col<UserSecret, String>,
    pub device_ids: __sdk::__query_builder::Col<UserSecret, Vec<String>>,
    pub permissions: __sdk::__query_builder::Col<UserSecret, Vec<String>>,
    pub created_at: __sdk::__query_builder::Col<UserSecret, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<UserSecret, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for UserSecret {
    type Cols = UserSecretCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserSecretCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            env: __sdk::__query_builder::Col::new(table_name, "env"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
            device_ids: __sdk::__query_builder::Col::new(table_name, "device_ids"),
            permissions: __sdk::__query_builder::Col::new(table_name, "permissions"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `UserSecret`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserSecretIxCols {
    pub env: __sdk::__query_builder::IxCol<UserSecret, String>,
    pub id: __sdk::__query_builder::IxCol<UserSecret, u64>,
    pub owner: __sdk::__query_builder::IxCol<UserSecret, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UserSecret {
    type IxCols = UserSecretIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserSecretIxCols {
            env: __sdk::__query_builder::IxCol::new(table_name, "env"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserSecret {}
