// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CreateFolderReducer from "./create_folder_reducer";
import DeleteDeviceReducer from "./delete_device_reducer";
import DeleteFileReducer from "./delete_file_reducer";
import DeleteSecretReducer from "./delete_secret_reducer";
import FinalizeUploadReducer from "./finalize_upload_reducer";
import RegisterDeviceReducer from "./register_device_reducer";
import RegisterFileReducer from "./register_file_reducer";
import RenameDeviceReducer from "./rename_device_reducer";
import RenameFileReducer from "./rename_file_reducer";
import RevokeApiKeyReducer from "./revoke_api_key_reducer";
import SetDeviceHostnameReducer from "./set_device_hostname_reducer";
import SetFileContentReducer from "./set_file_content_reducer";
import SetSecretReducer from "./set_secret_reducer";
import SetSecretDevicesReducer from "./set_secret_devices_reducer";
import SetSecretPermissionsReducer from "./set_secret_permissions_reducer";
import SetSecretValueReducer from "./set_secret_value_reducer";
import SignInReducer from "./sign_in_reducer";
import SignOutReducer from "./sign_out_reducer";
import SignUpReducer from "./sign_up_reducer";
import TouchDeviceReducer from "./touch_device_reducer";
import UpdateApiKeyPermissionsReducer from "./update_api_key_permissions_reducer";
import UpdateS3ConfigReducer from "./update_s_3_config_reducer";

// Import all procedure arg schemas
import * as ApiKeyHasPermissionProcedure from "./api_key_has_permission_procedure";
import * as CreateApiKeyProcedure from "./create_api_key_procedure";
import * as GetFileProcedure from "./get_file_procedure";
import * as GetSecretProcedure from "./get_secret_procedure";
import * as ReplaceFileContentProcedure from "./replace_file_content_procedure";
import * as RequestDownloadUrlProcedure from "./request_download_url_procedure";
import * as RequestUploadUrlProcedure from "./request_upload_url_procedure";
import * as RevealSecretProcedure from "./reveal_secret_procedure";
import * as SearchFilesProcedure from "./search_files_procedure";

// Import all table schema definitions
import DeviceRow from "./device_table";
import MyApiKeysRow from "./my_api_keys_table";
import MyDevicesRow from "./my_devices_table";
import MyFilesRow from "./my_files_table";
import MySecretsRow from "./my_secrets_table";
import MyUserRow from "./my_user_table";
import PasswordRow from "./password_table";
import PersonRow from "./person_table";
import S3ConfigStatusRow from "./s_3_config_status_table";
import UserRow from "./user_table";
import UserFileRow from "./user_file_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  device: __table({
    name: 'device',
    indexes: [
      { accessor: 'id', name: 'device_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner', name: 'device_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'device_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DeviceRow),
  password: __table({
    name: 'password',
    indexes: [
      { accessor: 'user', name: 'password_user_idx_btree', algorithm: 'btree', columns: [
        'user',
      ] },
    ],
    constraints: [
      { name: 'password_user_key', constraint: 'unique', columns: ['user'] },
    ],
  }, PasswordRow),
  person: __table({
    name: 'person',
    indexes: [
    ],
    constraints: [
    ],
  }, PersonRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'email', name: 'user_email_idx_btree', algorithm: 'btree', columns: [
        'email',
      ] },
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_file: __table({
    name: 'user_file',
    indexes: [
      { accessor: 'id', name: 'user_file_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'name', name: 'user_file_name_idx_btree', algorithm: 'btree', columns: [
        'name',
      ] },
      { accessor: 'owner', name: 'user_file_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'user_file_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserFileRow),
  my_api_keys: __table({
    name: 'my_api_keys',
    indexes: [
    ],
    constraints: [
    ],
  }, MyApiKeysRow),
  my_devices: __table({
    name: 'my_devices',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDevicesRow),
  my_files: __table({
    name: 'my_files',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFilesRow),
  my_secrets: __table({
    name: 'my_secrets',
    indexes: [
    ],
    constraints: [
    ],
  }, MySecretsRow),
  my_user: __table({
    name: 'my_user',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUserRow),
  s3_config_status: __table({
    name: 's_3_config_status',
    indexes: [
    ],
    constraints: [
    ],
  }, S3ConfigStatusRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("create_folder", CreateFolderReducer),
  __reducerSchema("delete_device", DeleteDeviceReducer),
  __reducerSchema("delete_file", DeleteFileReducer),
  __reducerSchema("delete_secret", DeleteSecretReducer),
  __reducerSchema("finalize_upload", FinalizeUploadReducer),
  __reducerSchema("register_device", RegisterDeviceReducer),
  __reducerSchema("register_file", RegisterFileReducer),
  __reducerSchema("rename_device", RenameDeviceReducer),
  __reducerSchema("rename_file", RenameFileReducer),
  __reducerSchema("revoke_api_key", RevokeApiKeyReducer),
  __reducerSchema("set_device_hostname", SetDeviceHostnameReducer),
  __reducerSchema("set_file_content", SetFileContentReducer),
  __reducerSchema("set_secret", SetSecretReducer),
  __reducerSchema("set_secret_devices", SetSecretDevicesReducer),
  __reducerSchema("set_secret_permissions", SetSecretPermissionsReducer),
  __reducerSchema("set_secret_value", SetSecretValueReducer),
  __reducerSchema("sign_in", SignInReducer),
  __reducerSchema("sign_out", SignOutReducer),
  __reducerSchema("sign_up", SignUpReducer),
  __reducerSchema("touch_device", TouchDeviceReducer),
  __reducerSchema("update_api_key_permissions", UpdateApiKeyPermissionsReducer),
  __reducerSchema("update_s_3_config", UpdateS3ConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("api_key_has_permission", ApiKeyHasPermissionProcedure.params, ApiKeyHasPermissionProcedure.returnType),
  __procedureSchema("create_api_key", CreateApiKeyProcedure.params, CreateApiKeyProcedure.returnType),
  __procedureSchema("get_file", GetFileProcedure.params, GetFileProcedure.returnType),
  __procedureSchema("get_secret", GetSecretProcedure.params, GetSecretProcedure.returnType),
  __procedureSchema("replace_file_content", ReplaceFileContentProcedure.params, ReplaceFileContentProcedure.returnType),
  __procedureSchema("request_download_url", RequestDownloadUrlProcedure.params, RequestDownloadUrlProcedure.returnType),
  __procedureSchema("request_upload_url", RequestUploadUrlProcedure.params, RequestUploadUrlProcedure.returnType),
  __procedureSchema("reveal_secret", RevealSecretProcedure.params, RevealSecretProcedure.returnType),
  __procedureSchema("search_files", SearchFilesProcedure.params, SearchFilesProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

