// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  deviceId: __t.u64().name("device_id"),
  recordedAt: __t.timestamp().name("recorded_at"),
  cpuPercent: __t.f32().name("cpu_percent"),
  ramUsedBytes: __t.u64().name("ram_used_bytes"),
  ramTotalBytes: __t.u64().name("ram_total_bytes"),
  swapUsedBytes: __t.u64().name("swap_used_bytes"),
  swapTotalBytes: __t.u64().name("swap_total_bytes"),
  netRxBytes: __t.u64().name("net_rx_bytes"),
  netTxBytes: __t.u64().name("net_tx_bytes"),
  storageUsedBytes: __t.u64().name("storage_used_bytes"),
  storageTotalBytes: __t.u64().name("storage_total_bytes"),
});
