// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  username: __t.string(),
  keyId: __t.u64().name("key_id"),
  deviceIds: __t.array(__t.string()).name("device_ids"),
  tags: __t.array(__t.string()),
  enabled: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  loginShell: __t.option(__t.string()).name("login_shell"),
});
