// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SshRelaySessionStatus,
} from "./types";


export default __t.row({
  id: __t.u64(),
  owner: __t.identity(),
  requesterDeviceId: __t.option(__t.u64()).name("requester_device_id"),
  relayDeviceId: __t.u64().name("relay_device_id"),
  endpointId: __t.u64().name("endpoint_id"),
  get status() {
    return SshRelaySessionStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  authToken: __t.option(__t.string()).name("auth_token"),
});
