// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32(),
  configured: __t.bool(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  pathPrefix: __t.option(__t.string()).name("path_prefix"),
  publicBaseUrl: __t.option(__t.string()).name("public_base_url"),
  hasAccessKeyId: __t.bool().name("has_access_key_id"),
  hasSecretAccessKey: __t.bool().name("has_secret_access_key"),
});
