// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  accessKeyId: __t.string().name("access_key_id"),
  secretAccessKey: __t.string().name("secret_access_key"),
  pathPrefix: __t.option(__t.string()).name("path_prefix"),
  publicBaseUrl: __t.option(__t.string()).name("public_base_url"),
});
