// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32(),
  configured: __t.bool(),
  enabled: __t.bool(),
  region: __t.string(),
  hasSecretKey: __t.bool().name("has_secret_key"),
  hasProjectId: __t.bool().name("has_project_id"),
  fromEmail: __t.string().name("from_email"),
  fromName: __t.string().name("from_name"),
});
