// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApiKey = __t.object("ApiKey", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  tokenHash: __t.string(),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type ApiKey = __Infer<typeof ApiKey>;

export const ApiKeyMetadata = __t.object("ApiKeyMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type ApiKeyMetadata = __Infer<typeof ApiKeyMetadata>;

export const CreatedApiKey = __t.object("CreatedApiKey", {
  token: __t.string(),
  get metadata() {
    return ApiKeyMetadata;
  },
});
export type CreatedApiKey = __Infer<typeof CreatedApiKey>;

export const Device = __t.object("Device", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  hostname: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.option(__t.timestamp()),
});
export type Device = __Infer<typeof Device>;

export const DeviceMetadata = __t.object("DeviceMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  hostname: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.option(__t.timestamp()),
});
export type DeviceMetadata = __Infer<typeof DeviceMetadata>;

export const FileMetadata = __t.object("FileMetadata", {
  id: __t.u64(),
  name: __t.string(),
  path: __t.option(__t.string()),
  hash: __t.string(),
  sizeBytes: __t.u64(),
  contentType: __t.option(__t.string()),
  inlineContent: __t.option(__t.string()),
  isDirectory: __t.bool(),
  s3Key: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileMetadata = __Infer<typeof FileMetadata>;

export const PasswordCredential = __t.object("PasswordCredential", {
  user: __t.identity(),
  passwordHash: __t.string(),
});
export type PasswordCredential = __Infer<typeof PasswordCredential>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const ReplaceTicket = __t.object("ReplaceTicket", {
  fileId: __t.u64(),
  uploadUrl: __t.string(),
  s3Key: __t.string(),
});
export type ReplaceTicket = __Infer<typeof ReplaceTicket>;

export const S3Config = __t.object("S3Config", {
  id: __t.u32(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  accessKeyId: __t.string(),
  secretAccessKey: __t.string(),
  pathPrefix: __t.option(__t.string()),
  publicBaseUrl: __t.option(__t.string()),
});
export type S3Config = __Infer<typeof S3Config>;

export const S3ConfigStatus = __t.object("S3ConfigStatus", {
  id: __t.u32(),
  configured: __t.bool(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  pathPrefix: __t.option(__t.string()),
  publicBaseUrl: __t.option(__t.string()),
  hasAccessKeyId: __t.bool(),
  hasSecretAccessKey: __t.bool(),
});
export type S3ConfigStatus = __Infer<typeof S3ConfigStatus>;

export const SecretMetadata = __t.object("SecretMetadata", {
  id: __t.u64(),
  env: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SecretMetadata = __Infer<typeof SecretMetadata>;

export const SecretValue = __t.object("SecretValue", {
  id: __t.u64(),
  env: __t.string(),
  value: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SecretValue = __Infer<typeof SecretValue>;

export const Session = __t.object("Session", {
  connection: __t.identity(),
  user: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const UploadTicket = __t.object("UploadTicket", {
  fileId: __t.u64(),
  uploadUrl: __t.string(),
  s3Key: __t.string(),
});
export type UploadTicket = __Infer<typeof UploadTicket>;

export const User = __t.object("User", {
  identity: __t.identity(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  role: __t.string(),
  createdAt: __t.timestamp(),
  lastLoginAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserFile = __t.object("UserFile", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  path: __t.option(__t.string()),
  hash: __t.string(),
  sizeBytes: __t.u64(),
  contentType: __t.option(__t.string()),
  inlineContent: __t.option(__t.string()),
  isDirectory: __t.bool(),
  s3Key: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserFile = __Infer<typeof UserFile>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  role: __t.string(),
  createdAt: __t.timestamp(),
  lastLoginAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const UserSecret = __t.object("UserSecret", {
  id: __t.u64(),
  owner: __t.identity(),
  env: __t.string(),
  value: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserSecret = __Infer<typeof UserSecret>;

