// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApiKey = __t.object("ApiKey", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  tokenHash: __t.string(),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type ApiKey = __Infer<typeof ApiKey>;

export const ApiKeyMetadata = __t.object("ApiKeyMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.option(__t.timestamp()),
  revokedAt: __t.option(__t.timestamp()),
});
export type ApiKeyMetadata = __Infer<typeof ApiKeyMetadata>;

export const CreatedApiKey = __t.object("CreatedApiKey", {
  token: __t.string(),
  get metadata() {
    return ApiKeyMetadata;
  },
});
export type CreatedApiKey = __Infer<typeof CreatedApiKey>;

export const Device = __t.object("Device", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  hostname: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.option(__t.timestamp()),
  metricsRetention: __t.option(__t.timeDuration()),
});
export type Device = __Infer<typeof Device>;

export const DeviceMetadata = __t.object("DeviceMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  hostname: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  lastSeenAt: __t.option(__t.timestamp()),
  metricsRetention: __t.option(__t.timeDuration()),
});
export type DeviceMetadata = __Infer<typeof DeviceMetadata>;

export const DeviceMetric = __t.object("DeviceMetric", {
  id: __t.u64(),
  deviceId: __t.u64(),
  recordedAt: __t.timestamp(),
  cpuPercent: __t.f32(),
  ramUsedBytes: __t.u64(),
  ramTotalBytes: __t.u64(),
  swapUsedBytes: __t.u64(),
  swapTotalBytes: __t.u64(),
  netRxBytes: __t.u64(),
  netTxBytes: __t.u64(),
  storageSyncRootUsedBytes: __t.u64(),
  storageSyncRootTotalBytes: __t.u64(),
  storageSystemUsedBytes: __t.u64(),
  storageSystemTotalBytes: __t.u64(),
  syncRootPath: __t.string(),
});
export type DeviceMetric = __Infer<typeof DeviceMetric>;

export const DeviceMetricSample = __t.object("DeviceMetricSample", {
  id: __t.u64(),
  deviceId: __t.u64(),
  recordedAt: __t.timestamp(),
  cpuPercent: __t.f32(),
  ramUsedBytes: __t.u64(),
  ramTotalBytes: __t.u64(),
  swapUsedBytes: __t.u64(),
  swapTotalBytes: __t.u64(),
  netRxBytes: __t.u64(),
  netTxBytes: __t.u64(),
  storageSyncRootUsedBytes: __t.u64(),
  storageSyncRootTotalBytes: __t.u64(),
  storageSystemUsedBytes: __t.u64(),
  storageSystemTotalBytes: __t.u64(),
  syncRootPath: __t.string(),
});
export type DeviceMetricSample = __Infer<typeof DeviceMetricSample>;

export const DeviceMetricsReport = __t.object("DeviceMetricsReport", {
  cpuPercent: __t.f32(),
  ramUsedBytes: __t.u64(),
  ramTotalBytes: __t.u64(),
  swapUsedBytes: __t.u64(),
  swapTotalBytes: __t.u64(),
  netRxBytes: __t.u64(),
  netTxBytes: __t.u64(),
  storageSyncRootUsedBytes: __t.u64(),
  storageSyncRootTotalBytes: __t.u64(),
  storageSystemUsedBytes: __t.u64(),
  storageSystemTotalBytes: __t.u64(),
  syncRootPath: __t.string(),
});
export type DeviceMetricsReport = __Infer<typeof DeviceMetricsReport>;

export const EmailVerification = __t.object("EmailVerification", {
  email: __t.string(),
  identity: __t.identity(),
  code: __t.string(),
  purpose: __t.string(),
  attempts: __t.u32(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  verifiedAt: __t.option(__t.timestamp()),
});
export type EmailVerification = __Infer<typeof EmailVerification>;

export const FileMetadata = __t.object("FileMetadata", {
  id: __t.u64(),
  name: __t.string(),
  treePath: __t.option(__t.string()),
  localPath: __t.option(__t.string()),
  hash: __t.string(),
  sizeBytes: __t.u64(),
  contentType: __t.option(__t.string()),
  isDirectory: __t.bool(),
  s3Key: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileMetadata = __Infer<typeof FileMetadata>;

export const PasswordCredential = __t.object("PasswordCredential", {
  user: __t.identity(),
  passwordHash: __t.string(),
});
export type PasswordCredential = __Infer<typeof PasswordCredential>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const ReplaceTicket = __t.object("ReplaceTicket", {
  fileId: __t.u64(),
  uploadUrl: __t.string(),
  s3Key: __t.string(),
});
export type ReplaceTicket = __Infer<typeof ReplaceTicket>;

export const S3Config = __t.object("S3Config", {
  id: __t.u32(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  accessKeyId: __t.string(),
  secretAccessKey: __t.string(),
  pathPrefix: __t.option(__t.string()),
  publicBaseUrl: __t.option(__t.string()),
});
export type S3Config = __Infer<typeof S3Config>;

export const S3ConfigStatus = __t.object("S3ConfigStatus", {
  id: __t.u32(),
  configured: __t.bool(),
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  pathPrefix: __t.option(__t.string()),
  publicBaseUrl: __t.option(__t.string()),
  hasAccessKeyId: __t.bool(),
  hasSecretAccessKey: __t.bool(),
});
export type S3ConfigStatus = __Infer<typeof S3ConfigStatus>;

export const ScalewayEmailConfig = __t.object("ScalewayEmailConfig", {
  id: __t.u32(),
  region: __t.string(),
  secretKey: __t.string(),
  projectId: __t.string(),
  fromEmail: __t.string(),
  fromName: __t.string(),
  enabled: __t.bool(),
});
export type ScalewayEmailConfig = __Infer<typeof ScalewayEmailConfig>;

export const ScalewayEmailConfigStatus = __t.object("ScalewayEmailConfigStatus", {
  id: __t.u32(),
  configured: __t.bool(),
  enabled: __t.bool(),
  region: __t.string(),
  hasSecretKey: __t.bool(),
  hasProjectId: __t.bool(),
  fromEmail: __t.string(),
  fromName: __t.string(),
});
export type ScalewayEmailConfigStatus = __Infer<typeof ScalewayEmailConfigStatus>;

export const SecretMetadata = __t.object("SecretMetadata", {
  id: __t.u64(),
  env: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SecretMetadata = __Infer<typeof SecretMetadata>;

export const SecretValue = __t.object("SecretValue", {
  id: __t.u64(),
  env: __t.string(),
  value: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SecretValue = __Infer<typeof SecretValue>;

export const Session = __t.object("Session", {
  connection: __t.identity(),
  user: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const SshEndpoint = __t.object("SshEndpoint", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  username: __t.string(),
  keyId: __t.u64(),
  deviceIds: __t.array(__t.string()),
  tags: __t.array(__t.string()),
  enabled: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  loginShell: __t.option(__t.string()),
});
export type SshEndpoint = __Infer<typeof SshEndpoint>;

export const SshEndpointMetadata = __t.object("SshEndpointMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  host: __t.string(),
  port: __t.u16(),
  username: __t.string(),
  keyId: __t.u64(),
  deviceIds: __t.array(__t.string()),
  tags: __t.array(__t.string()),
  enabled: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  loginShell: __t.option(__t.string()),
});
export type SshEndpointMetadata = __Infer<typeof SshEndpointMetadata>;

export const SshKey = __t.object("SshKey", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  publicKey: __t.string(),
  privateKey: __t.string(),
  fingerprint: __t.string(),
  deviceIds: __t.array(__t.string()),
  tags: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SshKey = __Infer<typeof SshKey>;

export const SshKeyMetadata = __t.object("SshKeyMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  publicKey: __t.string(),
  fingerprint: __t.string(),
  deviceIds: __t.array(__t.string()),
  tags: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SshKeyMetadata = __Infer<typeof SshKeyMetadata>;

export const SshKeyValue = __t.object("SshKeyValue", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  publicKey: __t.string(),
  privateKey: __t.string(),
  fingerprint: __t.string(),
  deviceIds: __t.array(__t.string()),
  tags: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SshKeyValue = __Infer<typeof SshKeyValue>;

export const SshRelayDevice = __t.object("SshRelayDevice", {
  owner: __t.identity(),
  deviceId: __t.u64(),
  updatedAt: __t.timestamp(),
  listenUrl: __t.option(__t.string()),
});
export type SshRelayDevice = __Infer<typeof SshRelayDevice>;

export const SshRelayDeviceMetadata = __t.object("SshRelayDeviceMetadata", {
  owner: __t.identity(),
  deviceId: __t.u64(),
  updatedAt: __t.timestamp(),
  listenUrl: __t.option(__t.string()),
});
export type SshRelayDeviceMetadata = __Infer<typeof SshRelayDeviceMetadata>;

export const SshRelaySession = __t.object("SshRelaySession", {
  id: __t.u64(),
  owner: __t.identity(),
  requesterDeviceId: __t.option(__t.u64()),
  relayDeviceId: __t.u64(),
  endpointId: __t.u64(),
  get status() {
    return SshRelaySessionStatus;
  },
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  authToken: __t.option(__t.string()),
});
export type SshRelaySession = __Infer<typeof SshRelaySession>;

export const SshRelaySessionMetadata = __t.object("SshRelaySessionMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  requesterDeviceId: __t.option(__t.u64()),
  relayDeviceId: __t.u64(),
  endpointId: __t.u64(),
  get status() {
    return SshRelaySessionStatus;
  },
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  authToken: __t.option(__t.string()),
});
export type SshRelaySessionMetadata = __Infer<typeof SshRelaySessionMetadata>;

// The tagged union or sum type for the algebraic type `SshRelaySessionStatus`.
export const SshRelaySessionStatus = __t.enum("SshRelaySessionStatus", {
  Pending: __t.unit(),
  Active: __t.unit(),
  Closed: __t.unit(),
});
export type SshRelaySessionStatus = __Infer<typeof SshRelaySessionStatus>;

export const UiCommand = __t.object("UiCommand", {
  id: __t.u64(),
  owner: __t.identity(),
  targetDeviceId: __t.option(__t.u64()),
  kind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
  handledAt: __t.option(__t.timestamp()),
  handledByDeviceId: __t.option(__t.u64()),
});
export type UiCommand = __Infer<typeof UiCommand>;

export const UiCommandMetadata = __t.object("UiCommandMetadata", {
  id: __t.u64(),
  owner: __t.identity(),
  targetDeviceId: __t.option(__t.u64()),
  kind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
  handledAt: __t.option(__t.timestamp()),
  handledByDeviceId: __t.option(__t.u64()),
});
export type UiCommandMetadata = __Infer<typeof UiCommandMetadata>;

export const UiEvent = __t.object("UiEvent", {
  owner: __t.identity(),
  targetDeviceId: __t.option(__t.u64()),
  commandId: __t.option(__t.u64()),
  kind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type UiEvent = __Infer<typeof UiEvent>;

export const UploadTicket = __t.object("UploadTicket", {
  fileId: __t.u64(),
  uploadUrl: __t.string(),
  s3Key: __t.string(),
});
export type UploadTicket = __Infer<typeof UploadTicket>;

export const User = __t.object("User", {
  identity: __t.identity(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  role: __t.string(),
  emailVerified: __t.bool(),
  createdAt: __t.timestamp(),
  lastLoginAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserFile = __t.object("UserFile", {
  id: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  treePath: __t.option(__t.string()),
  localPath: __t.option(__t.string()),
  hash: __t.string(),
  sizeBytes: __t.u64(),
  contentType: __t.option(__t.string()),
  isDirectory: __t.bool(),
  s3Key: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserFile = __Infer<typeof UserFile>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  displayName: __t.option(__t.string()),
  role: __t.string(),
  emailVerified: __t.bool(),
  createdAt: __t.timestamp(),
  lastLoginAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const UserSecret = __t.object("UserSecret", {
  id: __t.u64(),
  owner: __t.identity(),
  env: __t.string(),
  value: __t.string(),
  deviceIds: __t.array(__t.string()),
  permissions: __t.array(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserSecret = __Infer<typeof UserSecret>;

