// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  bucket: __t.string(),
  region: __t.string(),
  endpoint: __t.option(__t.string()),
  accessKeyId: __t.string(),
  secretAccessKey: __t.string(),
  pathPrefix: __t.option(__t.string()),
  publicBaseUrl: __t.option(__t.string()),
};
