// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  name: __t.string(),
  treePath: __t.option(__t.string()).name("tree_path"),
  localPath: __t.option(__t.string()).name("local_path"),
  hash: __t.string(),
  sizeBytes: __t.u64().name("size_bytes"),
  contentType: __t.option(__t.string()).name("content_type"),
  isDirectory: __t.bool().name("is_directory"),
  s3Key: __t.string().name("s_3_key"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
